-- Migration 016: Rename tables to conform to service prefix convention.
-- Rule: taskAuth → auth_ prefix.
-- NOTE: Guards check for OLD table name existing AND NEW table name NOT existing.
-- The global replace of accounts_→auth_ in Go code must NOT affect these guard conditions.

SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='accounts_user_access_token_audit') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='auth_user_access_token_audit'),'ALTER TABLE `accounts_user_access_token_audit` RENAME TO `auth_user_access_token_audit`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='accounts_user_access_token') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='auth_user_access_token'),'ALTER TABLE `accounts_user_access_token` RENAME TO `auth_user_access_token`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='accounts_kyc_audit_log') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='auth_kyc_audit_log'),'ALTER TABLE `accounts_kyc_audit_log` RENAME TO `auth_kyc_audit_log`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='accounts_aml_screening_record') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='auth_aml_screening_record'),'ALTER TABLE `accounts_aml_screening_record` RENAME TO `auth_aml_screening_record`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='accounts_email_registration_invite') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='auth_email_registration_invite'),'ALTER TABLE `accounts_email_registration_invite` RENAME TO `auth_email_registration_invite`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='accounts_registration_invite_code') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='auth_registration_invite_code'),'ALTER TABLE `accounts_registration_invite_code` RENAME TO `auth_registration_invite_code`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='accounts_sms_verification_code') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='auth_sms_verification_code'),'ALTER TABLE `accounts_sms_verification_code` RENAME TO `auth_sms_verification_code`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='accounts_recharge_sms_gate') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='auth_recharge_sms_gate'),'ALTER TABLE `accounts_recharge_sms_gate` RENAME TO `auth_recharge_sms_gate`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='accounts_user_profile') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='auth_user_profile'),'ALTER TABLE `accounts_user_profile` RENAME TO `auth_user_profile`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='accounts_kyc_profile') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='auth_kyc_profile'),'ALTER TABLE `accounts_kyc_profile` RENAME TO `auth_kyc_profile`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='accounts_registration_invite_policy') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='auth_registration_invite_policy'),'ALTER TABLE `accounts_registration_invite_policy` RENAME TO `auth_registration_invite_policy`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='accounts_kyc_limit_policy') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='auth_kyc_limit_policy'),'ALTER TABLE `accounts_kyc_limit_policy` RENAME TO `auth_kyc_limit_policy`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='accounts_login_method') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='auth_login_method'),'ALTER TABLE `accounts_login_method` RENAME TO `auth_login_method`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='accounts_customtoken') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='auth_customtoken'),'ALTER TABLE `accounts_customtoken` RENAME TO `auth_customtoken`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='accounts_super_admin') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='auth_super_admin'),'ALTER TABLE `accounts_super_admin` RENAME TO `auth_super_admin`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='accounts_user') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='auth_user'),'ALTER TABLE `accounts_user` RENAME TO `auth_user`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='accounts_referral_code') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='auth_referral_code'),'ALTER TABLE `accounts_referral_code` RENAME TO `auth_referral_code`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='accounts_referral_policy') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='auth_referral_policy'),'ALTER TABLE `accounts_referral_policy` RENAME TO `auth_referral_policy`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='oidc_client') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='auth_oidc_client'),'ALTER TABLE `oidc_client` RENAME TO `auth_oidc_client`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='oidc_authorization') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='auth_oidc_authorization'),'ALTER TABLE `oidc_authorization` RENAME TO `auth_oidc_authorization`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='django_content_type') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='auth_django_content_type'),'ALTER TABLE `django_content_type` RENAME TO `auth_django_content_type`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='system_feature_policy') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='auth_system_feature_policy'),'ALTER TABLE `system_feature_policy` RENAME TO `auth_system_feature_policy`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
