#!/usr/bin/env bash
# Self-test for check_conf_sync.sh (OPT-20260901-024):
#   1) clean tree passes,
#   2) a stale GENERATED fragment is detected (exit 1),
#   3) running the check leaves the real working tree untouched.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHECK="$HERE/check_conf_sync.sh"
RUNALL_SCRIPTS="$(cd "$HERE/../../.." && pwd)/runAll/scripts"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
cd "$TMP"

mkdir -p conf/core/email conf/events/domain-events db/scripts/ci runAll/scripts
printf 'scheme: https\n' > conf/base.yaml
printf 'host: smtp.example.com\nport: 465\n' > conf/core/email/config.yaml
cat > conf/events/domain-events/sync.manifest.yaml <<'EOF'
fragments:
  - from: ../../core/email/config.yaml
    to: email.yaml
    pick: [host]
EOF
cat > conf/events/domain-events/email.yaml <<'EOF'
# GENERATED by conf/events/domain-events/sync.sh — DO NOT EDIT
# source: conf/core/email/config.yaml
# synced_at: 2026-09-01T00:00:00Z
host: smtp.example.com
EOF
cp "$CHECK" db/scripts/ci/check_conf_sync.sh
for f in conf-sync-all.sh conf-sync.py conf_lib.py conf_local.py; do
  cp "$RUNALL_SCRIPTS/$f" runAll/scripts/
done

git init -q .
git add -A
git -c user.email=ci@example.invalid -c user.name=ci commit -qm seed

# 1) clean tree passes.
if ! bash db/scripts/ci/check_conf_sync.sh >/dev/null 2>&1; then
  echo "FAIL: clean tree should pass" >&2
  exit 1
fi

# 3) worktree untouched after the check.
if [[ -n "$(git status --porcelain)" ]]; then
  echo "FAIL: check_conf_sync modified the working tree" >&2
  git status --porcelain >&2
  exit 1
fi

# 2) stale GENERATED fragment detected.
cat > conf/events/domain-events/email.yaml <<'EOF'
# GENERATED by conf/events/domain-events/sync.sh — DO NOT EDIT
# source: conf/core/email/config.yaml
# synced_at: 2026-09-01T00:00:00Z
host: stale.example.com
EOF
if bash db/scripts/ci/check_conf_sync.sh >/dev/null 2>&1; then
  echo "FAIL: stale fragment should be detected" >&2
  exit 1
fi

echo "ok: check_conf_sync self-test passed"
