// Code generated by taskGateway/scripts/routes-to-apisix.py; DO NOT EDIT.

package gatewaycors

// AllowHeaders is the canonical CORS allow-headers list for taskGateway platform Go services.
const AllowHeaders = "Authorization, Content-Type, X-Trace-Id, X-Span-Id, X-Parent-Span-Id, traceparent, X-CSRFToken, X-Requested-With, Idempotency-Key"

// ExposeHeaders is the canonical Access-Control-Expose-Headers value for platform Go services.
// Exposing X-Trace-Id enables frontend data-traceId binding for error diagnostics.
const ExposeHeaders = "X-Trace-Id, X-Parent-Span-Id, traceparent"

// CORSAllowHeaderNames is the ordered header name list (codegen SSOT).
var CORSAllowHeaderNames = []string{
	"Authorization",
	"Content-Type",
	"X-Trace-Id",
	"X-Span-Id",
	"X-Parent-Span-Id",
	"traceparent",
	"X-CSRFToken",
	"X-Requested-With",
	"Idempotency-Key",
}
