export const testIds = {
  appConfig: {
    apiBaseUrl: 'data-testid ac-api-base-url',
    account: 'data-testid ac-account',
    accessToken: 'data-testid ac-access-token',
    sessionConfigured: 'data-testid ac-session-configured',
    loggedInAccount: 'data-testid ac-logged-in-account',
    logout: 'data-testid ac-logout',
    reloginForUserId: 'data-testid ac-relogin-for-user-id',
    addCaptureRule: 'data-testid ac-add-capture-rule',
    editCaptureRule: 'data-testid ac-edit-capture-rule',
    saveCaptureRule: 'data-testid ac-save-capture-rule',
    cancelCaptureRuleEdit: 'data-testid ac-cancel-capture-rule-edit',
    removeCaptureRule: 'data-testid ac-remove-capture-rule',
    captureRuleCard: 'data-testid ac-capture-rule-card',
    captureRuleEditor: 'data-testid ac-capture-rule-editor',
    captureRuleCompany: 'data-testid ac-capture-rule-company',
    captureRuleName: 'data-testid ac-capture-rule-name',
    captureRuleSummaryName: 'data-testid ac-capture-rule-summary-name',
    ingestToken: 'data-testid ac-ingest-token',
    errorReportUrl: 'data-testid ac-error-report-url',
    tenantId: 'data-testid ac-tenant-id',
    workspaceId: 'data-testid ac-workspace-id',
    lokiPollEnabled: 'data-testid ac-loki-poll-enabled',
    lokiDatasourceUid: 'data-testid ac-loki-datasource-uid',
    submit: 'data-testid ac-submit-form',
  },
  homeRedirect: {
    container: 'data-testid home-redirect-container',
  },
};
