<template>
  <div data-alias="cmp-onboarding" class="min-h-screen bg-background py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-lg mx-auto">
      <div class="bg-white rounded-2xl shadow-xl p-8 text-center">
        <!-- Icon/Illustration -->
        <div class="text-6xl mb-4">🏢</div>

        <h1 class="text-2xl font-bold text-text-dark mb-3">
          {{ existingCompany ? '确认您的公司名称' : '创建您的第一个公司' }}
        </h1>
        <p class="text-text-light mb-8">
          {{ existingCompany
            ? '系统已为您创建了公司，您可以在此修改公司名称后继续。'
            : '您还没有公司或工作空间。创建一个公司以开始使用各项服务。'
          }}
        </p>

        <form @submit.prevent="handleSubmit" class="space-y-4 text-left">
          <div>
            <label for="companyName" class="block text-sm font-medium text-text-light mb-2">
              公司名称
            </label>
            <input
              id="companyName"
              v-model="companyName"
              type="text"
              required
              placeholder="例如：我的团队"
              class="input w-full"
              :disabled="loading || checkingExisting"
              maxlength="255"
            />
          </div>

          <div
            v-if="errorMsg"
            class="text-sm text-error bg-error/10 rounded-lg p-3"
            :data-traceId="errorTraceId || undefined"
          >
            {{ errorMsg }}
          </div>

          <button
            type="submit"
            class="btn btn-primary w-full"
            :disabled="loading || checkingExisting || !companyName.trim()"
          >
            <span v-if="checkingExisting" class="inline-flex items-center gap-2">
              <span class="animate-spin">&#x21bb;</span> 正在检查...
            </span>
            <span v-else-if="loading" class="inline-flex items-center gap-2">
              <span class="animate-spin">&#x21bb;</span> {{ existingCompany ? '正在保存...' : '正在创建...' }}
            </span>
            <span v-else>{{ existingCompany ? '确认公司名称' : '创建公司' }}</span>
          </button>
        </form>
      </div>
    </div>
  </div>
</template>

<script>
import { apiFetch } from '../utils/apiUtils'
import { extractTraceId } from '../utils/traceId.js'
import { setUserCompanies } from '../utils/sharedUserTenantCache'
import { resolveAuthenticatedUserId } from '../utils/sessionUserIdUtils.js'
import {
  defaultOnboardingCompanyName,
  extractProfileDisplayName,
  isAutoGeneratedCompanyName,
} from '../utils/onboardingCompanyName.js'

export default {
  name: 'OnboardingPage',
  data() {
    return {
      companyName: '',
      existingCompany: null, // { company_id, name } if user already has a company
      checkingExisting: true,
      loading: false,
      errorMsg: '',
      errorTraceId: '',
    }
  },
  async mounted() {
    // 平台角色（super_admin/employee）直接去系统管理，绝不进入公司创建引导。
    // 防御兜底：登录重定向已处理，此处覆盖手动输入 /onboarding/ 或陈旧链接场景。
    try {
      const rolesResp = await apiFetch('/api/auth/user-roles/', {
        credentials: 'include',
        headers: { Accept: 'application/json' },
      })
      if (rolesResp.ok) {
        const rolesBody = await rolesResp.json()
        const roles = (rolesBody?.roles || []).map((r) => r?.role).filter(Boolean)
        if (roles.some((r) => ['super_admin', 'employee'].includes(r))) {
          window.location.href = '/system-admin/'
          return
        }
      } else if (rolesResp.status === 401) {
        // 未登录（无有效会话）→ 跳转登录页。
        // 不携带 next=/onboarding/：该 next 会被微信扫码回调无条件回显，导致
        // 「已设置公司名的用户第二次扫码登录依旧跳到公司名称设置页」死循环
        // （登录后落点交由后端按角色计算：有公司→work-panel，无公司→onboarding）。
        window.location.href = '/auth/login/'
        return
      }
    } catch (_) {
      // 角色查询失败不阻断引导页主流程
    }
    await this.checkExistingCompany()
  },
  methods: {
    async checkExistingCompany() {
      // 已激活用户（账号切换/OIDC 登录）的 userId 可能是 HttpOnly cookie，
      // 对 JS 不可见 — 用 localStorage→cookie→profile API 全链路解析，
      // 避免误入「创建模式」而非「确认公司名」
      const userId = await resolveAuthenticatedUserId()
      if (!userId) {
        this.companyName = defaultOnboardingCompanyName('')
        this.checkingExisting = false
        return
      }
      try {
        const [displayName, list] = await Promise.all([
          this.fetchProfileDisplayName(),
          this.fetchCreatorCompanies(userId),
        ])
        const defaultName = defaultOnboardingCompanyName(displayName)
        if (list.length > 0) {
          this.existingCompany = { company_id: list[0].id, name: list[0].name }
          const existingName = list[0].name || ''
          this.companyName = isAutoGeneratedCompanyName(existingName, displayName)
            ? defaultName
            : existingName
        } else {
          this.companyName = defaultName
        }
      } catch (_) {
        // If we can't check, fall back to create mode with formula default
        this.companyName = defaultOnboardingCompanyName(await this.fetchProfileDisplayName())
      } finally {
        this.checkingExisting = false
      }
    },

    async fetchProfileDisplayName() {
      try {
        const resp = await apiFetch('/api/accounts/users/profile/', {
          credentials: 'include',
          headers: { Accept: 'application/json' },
        })
        if (!resp.ok) return ''
        const profile = await resp.json()
        return extractProfileDisplayName(profile)
      } catch (_) {
        return ''
      }
    },

    async fetchCreatorCompanies(userId) {
      const resp = await apiFetch(
        `/api/tenant/_/accounts/companies/by-creator?creator_id=${encodeURIComponent(userId)}`,
        { headers: { Accept: 'application/json' } },
      )
      if (!resp.ok) return []
      const list = await resp.json()
      return Array.isArray(list) ? list : []
    },

    async handleSubmit() {
      const name = this.companyName.trim()
      if (!name) {
        this.errorMsg = '请输入公司名称'
        return
      }
      this.loading = true
      this.errorMsg = ''
      this.errorTraceId = ''

      try {
        if (this.existingCompany) {
          // Rename existing company
          await this.renameCompany(this.existingCompany.company_id, name)
        } else {
          // Create new company
          await this.createCompany(name)
        }
      } catch (err) {
        this.errorMsg = err.message || '操作失败，请稍后重试'
        this.errorTraceId = extractTraceId(err) || ''
      } finally {
        this.loading = false
      }
    },

    async createCompany(name) {
      // tid 占位 _：创建端点不依赖公司维度（OPT-044 新式路径），网关仅透传
      const resp = await apiFetch('/api/tenant/_/accounts/companies/', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name }),
      })
      if (!resp.ok) {
        // 提交时凭据失效（微信回调凭据补全失败/过期等）→ 跳登录页。
        // 不带 next=/onboarding/ 回跳：该 next 会被扫码回调无条件回显，令
        // 有公司用户反复落入引导页（登录后按角色计算落点：有公司→work-panel）。
        // 此前带 next 保留回跳，避免停留在表单反复报「服务器错误 (401)」死循环
        // （凭据补全链为异步，任何一步失败都会留下无凭据会话，此处为最终恢复路径）。
        if (resp.status === 401) {
          window.location.href = '/auth/login/'
          const err = new Error('登录状态已失效，正在跳转登录…')
          err.traceId = resp.traceId || ''
          throw err
        }
        const data = await resp.json().catch(() => ({}))
        const err = new Error(data.detail || `服务器错误 (${resp.status})`)
        err.traceId = data._traceId || resp.traceId || ''
        err._errorData = data
        throw err
      }
      const result = await resp.json()
      const companyId = result.company_id
      setUserCompanies([String(companyId)])
      window.location.href = `/tenant/${companyId}/work-panel/`
    },

    async renameCompany(companyId, name) {
      const request = () =>
        apiFetch('/api/tenant/_/accounts/companies/', {
          method: 'PATCH',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ company_id: companyId, name }),
        })
      // PDP 权限缓存短 TTL（~2s）窗口内，公司创建者/管理员改名可能瞬时 403：
      // 自动重试 1 次（间隔 ~1s，覆盖陈旧窗口主要风险段），避免用户陷入死胡同。
      let resp = await request()
      if (resp.status === 403) {
        await new Promise((resolve) => setTimeout(resolve, 1000))
        resp = await request()
      }
      if (!resp.ok) {
        if (resp.status === 401) {
          // 同 createCompany：不带 next=/onboarding/，避免有公司用户扫码登录后仍回引导页
          window.location.href = '/auth/login/'
          const err = new Error('登录状态已失效，正在跳转登录…')
          err.traceId = resp.traceId || ''
          throw err
        }
        const data = await resp.json().catch(() => ({}))
        const baseMsg = data.detail || data.error || `服务器错误 (${resp.status})`
        // 重试后仍 403 → 权限同步尚未生效，给出可操作的提示而非通用错误
        const err = new Error(
          resp.status === 403 ? `权限尚未同步，请稍后重试（${baseMsg}）` : baseMsg,
        )
        err.traceId = data._traceId || resp.traceId || ''
        err._errorData = data
        throw err
      }
      const result = await resp.json()
      setUserCompanies([String(companyId)])
      window.location.href = `/tenant/${companyId}/work-panel/`
    },
  },
}
</script>
