import { computed, watch } from 'vue'
import { hasActiveCommentCloneProgress } from '../utils/commentCloneProgressFromLogs.js'

export function useTaskDetailRuntimeSectionBindings(ctx) {
  const {
    localTask,
    workspaceId,
    sseConnection,
    updateServerStatus,
    statusMessage,
    statusCommentId,
    statusRuntimeStatus,
    statusProgress,
    statusLogs,
    serverStatus,
    isServerRunning,
    isServerStarting,
    cloudRuntimeStatus,
    serverUrl,
    containerVscodeUrl,
    containerPageUrl,
    containerHeartbeatStatus,
    pauseContainerHeartbeatForRelayStop,
    resumeContainerHeartbeatForRelayStart,
    appendContainerHeartbeatLogLines,
    fetchTaskDetail,
    relayStartBlockedByUnboundOAuth,
    relayStartBlockedByOAuthCheckLoading,
    projectServerRunTemplate,
    effectiveTenantId,
    effectiveTaskId,
    isEditing,
    taskProjectsWithDetails,
    editingTask,
    containerEndpointRegistered,
    relayToTraeEnabled,
    repoCloneIdentitySaveError,
    recloneLoadingByUrl,
    repoRecloneGlobalLoading,
    recloneStatusByUrl,
    repoCloneIdentityByUrl,
    layerGitIdentityOptions,
    repoCloneIdentitySaving,
    layerGitIdentityLoading,
    cloneProgressEntryByRepoMatchKey,
    gitCloneRefMatchKey,
    repoCloneFieldId,
    cloneProgressRowHasSubPhases,
    cloneProgressRecvPct,
    cloneProgressUnpackPct,
    cloneProgressBarWidthTransitionClass,
    bootstrapCloneDone,
    bootstrapCloneLogFull,
    bootstrapCloneLogSegments,
    workspaceProjects,
    workspaceProjectsLoading,
    getProjectRepos,
    getRepoBranchValue,
    getRepoBranches,
    getRepoBranchError,
    isLoadingRepoBranches,
    selectedLayerGraphFileTreeLayerId,
    layerRepoGitIdentityLoading,
    layerRepoGitIdentityFetchError,
    perRepoGitIdentitySyncing,
    perRepoGitIdentitySyncError,
    staleRepoSyncLoading,
    staleRepoSyncError,
    staleRepoSyncNeedsReclone,
    containerGitIdentityLineForRepoUrl,
    gitOAuthCatalogVersion,
    onRepoOAuthReadiness,
    containerHttpUnreachable,
    sseLive,
    sseReconnecting,
    sseReconnectAttempts,
    ssePlatformRestartHint,
    containerHeartbeatLastSuccess,
    containerHeartbeatAttempts,
    containerHeartbeatError,
    containerHeartbeatSeqInfo,
    containerHeartbeatLogLines,
    displayComments,
    activeContainerAgentId,
    runtimeSectionRef,
    serverConfigRef,
    linkedProjectsPanelRef,
  } = ctx

  const runtimeSectionProps = computed(() => ({
    task: localTask.value,
    workspaceId: workspaceId.value,
    sseConnection: sseConnection.value,
    updateServerStatus,
    statusMessage: statusMessage.value,
    statusCommentId: statusCommentId?.value ?? '',
    statusRuntimeStatus: statusRuntimeStatus?.value ?? '',
    statusProgress: statusProgress.value,
    statusLogs: statusLogs.value,
    serverStatus: serverStatus.value,
    isServerRunning: isServerRunning.value,
    isServerStarting: isServerStarting.value,
    runtimeStatus: cloudRuntimeStatus?.value ?? '',
    serverUrl: serverUrl.value,
    containerVscodeUrl: containerVscodeUrl.value,
    containerPageUrl: containerPageUrl.value,
    containerHeartbeatStatus: containerHeartbeatStatus.value,
    pauseContainerHeartbeatForRelayStop,
    resumeContainerHeartbeatForRelayStart,
    appendContainerHeartbeatLogLines,
    refreshTaskDetail: fetchTaskDetail,
    startBlockedByUnboundOAuth: relayStartBlockedByUnboundOAuth.value,
    startBlockedByOAuthCheckLoading: relayStartBlockedByOAuthCheckLoading.value,
    projectServerRunTemplate: projectServerRunTemplate.value,
    displayComments: displayComments?.value || [],
    activeContainerAgentId: String(activeContainerAgentId?.value || ''),
    tenantId: String(effectiveTenantId.value || ''),
    taskId: String(effectiveTaskId.value || ''),
    isEditing: isEditing.value,
    taskProjectsWithDetails: taskProjectsWithDetails.value,
    editingTask: editingTask.value,
    containerEndpointRegistered: containerEndpointRegistered.value,
    relayToTraeEnabled: relayToTraeEnabled.value,
    repoCloneIdentitySaveError: repoCloneIdentitySaveError.value,
    recloneLoadingByUrl: recloneLoadingByUrl.value,
    repoRecloneGlobalLoading: repoRecloneGlobalLoading.value,
    recloneStatusByUrl: recloneStatusByUrl.value,
    repoCloneIdentityByUrl: repoCloneIdentityByUrl.value,
    layerGitIdentityOptions: layerGitIdentityOptions.value,
    repoCloneIdentitySaving: repoCloneIdentitySaving.value,
    layerGitIdentityLoading: layerGitIdentityLoading.value,
    cloneProgressEntryByRepoMatchKey: cloneProgressEntryByRepoMatchKey.value,
    gitCloneRefMatchKey,
    repoCloneFieldId,
    cloneProgressRowHasSubPhases,
    cloneProgressRecvPct,
    cloneProgressUnpackPct,
    cloneProgressBarWidthTransitionClass: cloneProgressBarWidthTransitionClass.value,
    bootstrapCloneDone: Boolean(bootstrapCloneDone?.value),
    bootstrapCloneLogFull: String(bootstrapCloneLogFull?.value ?? ''),
    bootstrapCloneLogSegments: Array.isArray(bootstrapCloneLogSegments?.value)
      ? bootstrapCloneLogSegments.value
      : null,
    workspaceProjects: workspaceProjects.value,
    workspaceProjectsLoading: workspaceProjectsLoading.value,
    getProjectRepos,
    getRepoBranchValue,
    getRepoBranches,
    getRepoBranchError,
    isLoadingRepoBranches,
    selectedLayerGraphFileTreeLayerId: selectedLayerGraphFileTreeLayerId.value,
    layerRepoGitIdentityLoading: layerRepoGitIdentityLoading.value,
    layerRepoGitIdentityFetchError: layerRepoGitIdentityFetchError.value,
    perRepoGitIdentitySyncing: perRepoGitIdentitySyncing.value,
    perRepoGitIdentitySyncError: perRepoGitIdentitySyncError.value,
    staleRepoSyncLoading: staleRepoSyncLoading.value,
    staleRepoSyncError: staleRepoSyncError.value,
    staleRepoSyncNeedsReclone: staleRepoSyncNeedsReclone.value,
    containerGitIdentityLineForRepoUrl,
    gitOAuthCatalogVersion: gitOAuthCatalogVersion.value,
    onReadinessChange: onRepoOAuthReadiness,
    showContainerHttpUnreachableBanner: Boolean(
      localTask.value && containerEndpointRegistered.value && containerHttpUnreachable.value,
    ),
    sseLive: sseLive.value,
    sseReconnecting: sseReconnecting.value,
    sseReconnectAttempts: sseReconnectAttempts.value,
    ssePlatformRestartHint: Boolean(ssePlatformRestartHint?.value),
    containerHeartbeatLastSuccess: containerHeartbeatLastSuccess.value,
    containerHeartbeatAttempts: containerHeartbeatAttempts.value,
    containerHeartbeatError: containerHeartbeatError.value,
    containerHeartbeatSeqInfo: containerHeartbeatSeqInfo.value,
    containerHeartbeatLogLines: containerHeartbeatLogLines.value,
  }))

  watch(runtimeSectionRef, (section) => {
    serverConfigRef.value = section?.serverConfigRef ?? null
    linkedProjectsPanelRef.value = section?.linkedProjectsPanelRef ?? null
  }, { flush: 'post' })

  return { runtimeSectionProps }
}

export function useTaskDetailCommentsSectionBindings(ctx) {
  const {
    localTask,
    taskRepoRows,
    containerCloneProgressEntries,
    containerCloneProgressByCommentId,
    recloneLoadingByUrl,
    recloneStatusByUrl,
    recloneErrorTraceIdByUrl,
    repoRecloneGlobalLoading,
    repoCloneFieldId,
    shortCloneRepoLabel,
    cloneProgressRowHasSubPhases,
    cloneProgressRecvPct,
    cloneProgressUnpackPct,
    cloneProgressBarWidthTransitionClass,
    cloneProgressRowLogIsPlaceholder,
    cloneProgressRowLogDisplayText,
    projectServerRunTemplate,
    taskProjectsWithDetails,
    repoCloneIdentityByUrl,
    displayComments,
    collaboratorNameById,
    collaboratorAvatarById,
    commentsHasMore,
    commentsFeedsLoadingMore,
    aiStreamBusy,
    aiStreamBuffer,
    activeContainerAgentId,
    bindingStatusFor,
    bindingCscIdFor,
    bindingContainerNameFor,
    commentHasLiveBinding,
    commentOwnsSharedContainer,
    bindingStartTraceIdFor,
    buildPerBindingServerStatusProps,
    markBindingReconnecting,
    cancelWaitingPreviousBinding,
    isCancelWaitingBusy,
    zTreeLogTargets,
    layerAgentStepCards,
    effectiveTenantId,
    effectiveWorkspaceId,
    effectiveTaskId,
    containerPageLinkPendingReveal,
    containerHttpUnreachable,
    displayContainerVscodeUrl,
    commentComposerChips,
    serverRuntimeNotServing,
    containerHeartbeatPaused,
    containerBootstrapFailureMessage,
    containerBootstrapFailureTraceId,
    containerBootstrapCloneLogFull,
    containerLayerGraphAuthInvalid,
    containerPageUrl,
    layerGraphZNodes,
    layerGraphRefreshing,
    layerGraphMetaLine,
    layerGraphBusyActionKey,
    selectedLayerGraphNode,
    selectedZTreeLayerChangesPanel,
    selectedLayerGraphFileTreeLayerId,
    layerChangesRefreshBusy,
    layerChangesRefreshEnabled,
    layerChangesRefreshError,
    layerChangesRefreshErrorTraceId,
    layerChangesGitStagedActionsBlocked,
    layerChangesGitCommitIdentityBlocked,
    containerEndpointRegistered,
    projectFileTreeRefreshNonce,
    layerGraphModelSelectDisabled,
    layerGraphModelOptions,
    layerGraphDefaultModel,
    layerGraphEditRunTargetJobId,
    layerGraphModelLoadError,
    layerGraphModelLoadErrorTraceId,
    layerGraphCmdError,
    layerGraphCmdErrorTraceId,
    layerGraphCmdSending,
    containerActionsBlocked,
    layerExecLogLoading,
    layerExecLogCopyable,
    layerExecLogClearable,
    layerExecLogCopyFeedback,
    layerExecLogTopError,
    layerCloneLogFetchError,
    layerCloneLogFetchErrorTraceId,
    layerCloneLogText,
    layerLiveOutputDisplay,
    layerJobLogFetchError,
    layerJobLogFetchErrorTraceId,
    layerJobExecutionPayload,
    layerJobCommandHead,
    layerJobOutputDisplay,
    layerAgentStepCopyFeedbackKey,
    sseLive,
    sseReconnecting,
    sseReconnectAttempts,
    ssePlatformRestartHint,
    layerPanelStore,
    layerGitIdentityOptions,
    repoOAuthReadiness,
  } = ctx

  const commentsSectionProps = computed(() => ({
    // 评论级进度条已生效（任一评论有 live clone map）时收起任务级横幅，避免同一进度两处展示（OPT-20260815-019）
    showContainerCloneProgressBanner:
      taskRepoRows.value.length === 0 &&
      containerCloneProgressEntries.value.length > 0 &&
      !hasActiveCommentCloneProgress(containerCloneProgressByCommentId?.value),
    containerCloneProgressEntries: containerCloneProgressEntries.value,
    cloneProgressByCommentId: containerCloneProgressByCommentId?.value || {},
    recloneLoadingByUrl: recloneLoadingByUrl?.value || {},
    recloneStatusByUrl: recloneStatusByUrl?.value || {},
    recloneErrorTraceIdByUrl: recloneErrorTraceIdByUrl?.value || {},
    repoRecloneGlobalLoading: Boolean(repoRecloneGlobalLoading?.value),
    repoCloneFieldId,
    shortCloneRepoLabel,
    cloneProgressRowHasSubPhases,
    cloneProgressRecvPct,
    cloneProgressUnpackPct,
    cloneProgressBarWidthTransitionClass: cloneProgressBarWidthTransitionClass.value,
    cloneProgressRowLogIsPlaceholder,
    cloneProgressRowLogDisplayText,
    displayComments: displayComments.value,
    collaboratorNameById: collaboratorNameById?.value || {},
    collaboratorAvatarById: collaboratorAvatarById?.value || {},
    // OPT-20260816-002: 评论区复用 useTaskDetail 单一绑定实例，避免重复拉取/轮询
    bindingStatusFor,
    bindingCscIdFor,
    bindingContainerNameFor,
    commentHasLiveBinding,
    commentOwnsSharedContainer,
    bindingStartTraceIdFor,
    buildPerBindingServerStatusProps,
    markBindingReconnecting,
    cancelWaitingPreviousBinding,
    isCancelWaitingBusy,
    commentsFeedErrors: localTask.value?.comments_feed_errors || [],
    commentsHasMore: commentsHasMore.value,
    commentsLoadingMore: commentsFeedsLoadingMore.value,
    aiStreamBusy: aiStreamBusy.value,
    aiStreamBuffer: aiStreamBuffer.value,
    activeContainerAgentId: String(activeContainerAgentId?.value || ''),
    hasZtreeAgentSteps: Boolean(zTreeLogTargets.value.jobId),
    agentStepCount: layerAgentStepCards.value.length,
    tenantId: String(effectiveTenantId.value || ''),
    workspaceId: String(effectiveWorkspaceId.value || ''),
    taskId: String(effectiveTaskId.value || ''),
    task: localTask.value,
    containerPageLinkPendingReveal: containerPageLinkPendingReveal.value,
    containerHttpUnreachable: containerHttpUnreachable.value,
    displayContainerVscodeUrl: displayContainerVscodeUrl.value,
    commentComposerChips: commentComposerChips.value,
    serverRuntimeNotServing: serverRuntimeNotServing?.value ?? false,
    containerHeartbeatPaused: containerHeartbeatPaused?.value ?? false,
    containerBootstrapFailureMessage: containerBootstrapFailureMessage?.value ?? '',
    containerBootstrapFailureTraceId: containerBootstrapFailureTraceId?.value ?? '',
    bootstrapCloneLogText: containerBootstrapCloneLogFull?.value ?? '',
    containerLayerGraphAuthInvalid: containerLayerGraphAuthInvalid?.value ?? false,
    containerPageUrl: containerPageUrl.value,
    layerGraphZNodes: layerGraphZNodes.value,
    layerGraphRefreshing: layerGraphRefreshing.value,
    layerGraphMetaLine: layerGraphMetaLine.value,
    layerGraphBusyActionKey: layerGraphBusyActionKey.value,
    selectedLayerGraphNode: selectedLayerGraphNode.value,
    selectedZTreeLayerChangesPanel: selectedZTreeLayerChangesPanel.value,
    selectedLayerGraphFileTreeLayerId: selectedLayerGraphFileTreeLayerId.value,
    layerChangesRefreshBusy: layerChangesRefreshBusy.value,
    layerChangesRefreshEnabled: layerChangesRefreshEnabled.value,
    layerChangesRefreshError: layerChangesRefreshError.value,
    layerChangesRefreshErrorTraceId: layerChangesRefreshErrorTraceId?.value ?? '',
    layerChangesGitStagedActionsBlocked: layerChangesGitStagedActionsBlocked.value,
    layerChangesGitCommitIdentityBlocked: layerChangesGitCommitIdentityBlocked.value,
    containerEndpointRegistered: containerEndpointRegistered.value,
    projectFileTreeRefreshNonce: projectFileTreeRefreshNonce.value,
    layerGraphModelSelectDisabled: layerGraphModelSelectDisabled.value,
    layerGraphModelOptions: layerGraphModelOptions.value,
    layerGraphDefaultModel: layerGraphDefaultModel.value,
    layerGraphEditRunTargetJobId: layerGraphEditRunTargetJobId.value,
    layerGraphModelLoadError: layerGraphModelLoadError.value,
    layerGraphModelLoadErrorTraceId: layerGraphModelLoadErrorTraceId?.value ?? '',
    layerGraphCmdError: layerGraphCmdError.value,
    layerGraphCmdErrorTraceId: layerGraphCmdErrorTraceId?.value ?? '',
    layerGraphCmdSending: layerGraphCmdSending.value,
    containerActionsBlocked: containerActionsBlocked.value,
    layerExecLogLoading: layerExecLogLoading.value,
    layerExecLogCopyable: layerExecLogCopyable.value,
    layerExecLogClearable: layerExecLogClearable.value,
    layerExecLogCopyFeedback: layerExecLogCopyFeedback.value,
    layerExecLogTopError: layerExecLogTopError.value,
    zTreeLogTargets: zTreeLogTargets.value,
    layerCloneLogFetchError: layerCloneLogFetchError.value,
    layerCloneLogFetchErrorTraceId: layerCloneLogFetchErrorTraceId.value,
    layerCloneLogText: layerCloneLogText.value,
    layerLiveOutputDisplay: layerLiveOutputDisplay.value,
    layerJobLogFetchError: layerJobLogFetchError.value,
    layerJobLogFetchErrorTraceId: layerJobLogFetchErrorTraceId.value,
    layerJobExecutionPayload: layerJobExecutionPayload.value,
    layerJobCommandHead: layerJobCommandHead.value,
    layerJobOutputDisplay: layerJobOutputDisplay.value,
    layerAgentStepCopyFeedbackKey: layerAgentStepCopyFeedbackKey.value,
    layerAgentStepCards: layerAgentStepCards.value,
    sseLive: sseLive?.value ?? false,
    sseReconnecting: sseReconnecting?.value ?? false,
    sseReconnectAttempts: sseReconnectAttempts?.value ?? 0,
    ssePlatformRestartHint: ssePlatformRestartHint?.value ?? false,
    projectServerRunTemplate: projectServerRunTemplate?.value ?? null,
    taskProjectsWithDetails: Array.isArray(taskProjectsWithDetails?.value)
      ? taskProjectsWithDetails.value
      : [],
    taskRepoRows: Array.isArray(taskRepoRows?.value) ? taskRepoRows.value : [],
    repoCloneIdentityByUrl: repoCloneIdentityByUrl?.value || {},
    layerPanelByCommentId: layerPanelStore?.state?.value || {},
    gitIdentityOptions: Array.isArray(layerGitIdentityOptions?.value)
      ? layerGitIdentityOptions.value
      : [],
    repoOAuthReadiness: repoOAuthReadiness?.value || null,
  }))

  return { commentsSectionProps }
}
