package main

import (
	"os"
	"path/filepath"
	"testing"

	"gopkg.in/yaml.v3"
)

const taskBillFragmentRel = "conf/task-referral/task-bill.yaml"

func writeTaskBillFragment(t *testing.T, root, secret string) {
	t.Helper()
	path := filepath.Join(root, taskBillFragmentRel)
	orig, origErr := os.ReadFile(path)
	t.Cleanup(func() {
		if origErr != nil {
			_ = os.Remove(path)
			return
		}
		_ = os.WriteFile(path, orig, 0o644)
	})
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	body := "# GENERATED by conf/task-referral/sync.sh — DO NOT EDIT\n" +
		"# source: conf/billing/task-bill/config.yaml\n" +
		"internalSecret: " + secret + "\n"
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func TestLoadBillInternalSecretFromFragment(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "conf", "task-referral"), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("TASKBILL_INTERNAL_SECRET", "")
	writeTaskBillFragment(t, root, "synced-bill-secret")
	got := loadBillInternalSecret(root)
	if got != "synced-bill-secret" {
		t.Fatalf("got %q, want fragment secret — loadBillInternalSecret 未读 task-bill.yaml", got)
	}
}

func TestLoadBillInternalSecretEnvWinsOverFragment(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "conf", "task-referral"), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("TASKBILL_INTERNAL_SECRET", "env-bill-secret")
	writeTaskBillFragment(t, root, "fragment-bill-secret")
	got := loadBillInternalSecret(root)
	if got != "env-bill-secret" {
		t.Fatalf("got %q, want env override", got)
	}
}

func TestLoadBillInternalSecretConfLocalOverlayWins(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "conf", "task-referral"), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("TASKBILL_INTERNAL_SECRET", "")
	writeTaskBillFragment(t, root, "tracked-empty-or-stale")
	localDir := filepath.Join(root, "conf-local", "task-referral")
	if err := os.MkdirAll(localDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(localDir, "task-bill.yaml"), []byte("internalSecret: from-conf-local\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	got := loadBillInternalSecret(root)
	if got != "from-conf-local" {
		t.Fatalf("got %q, want conf-local overlay", got)
	}
}

func TestSyncManifestDeclaresTaskBillFragment(t *testing.T) {
	root, err := findMonorepoRoot()
	if err != nil {
		t.Fatalf("findMonorepoRoot: %v", err)
	}
	data, err := os.ReadFile(filepath.Join(root, "conf", "task-referral", "sync.manifest.yaml"))
	if err != nil {
		t.Fatalf("read sync.manifest.yaml: %v", err)
	}
	var manifest struct {
		Fragments []struct {
			From string   `yaml:"from"`
			To   string   `yaml:"to"`
			Pick []string `yaml:"pick"`
		} `yaml:"fragments"`
	}
	if err := yaml.Unmarshal(data, &manifest); err != nil {
		t.Fatalf("parse: %v", err)
	}
	for _, f := range manifest.Fragments {
		if f.From == "../billing/task-bill/config.yaml" && f.To == "task-bill.yaml" {
			for _, k := range f.Pick {
				if k == "internalSecret" {
					return
				}
			}
		}
	}
	t.Fatal("sync.manifest.yaml 缺少 from ../billing/task-bill/config.yaml 且 pick internalSecret")
}
