#!/usr/bin/env python3
"""Shared helpers for monorepo conf/ layout."""
from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    yaml = None  # type: ignore


def _explicit_config_root(raw: str) -> Path | None:
    """CONF_ROOT may be the conf dir (has base.yaml) or deploy root (has conf/base.yaml)."""
    text = (raw or "").strip()
    if not text:
        return None
    p = Path(text).expanduser()
    if (p / "base.yaml").is_file():
        return p.parent.resolve()
    if (p / "conf" / "base.yaml").is_file():
        return p.resolve()
    return None


def repo_root() -> Path:
    import os

    for key in ("CONF_ROOT", "DEPLOY_ROOT"):
        hit = _explicit_config_root(os.environ.get(key, ""))
        if hit is not None:
            return hit

    anchors = [
        Path.cwd(),
        Path(__file__).resolve(),
    ]
    for start in anchors:
        here = start if start.is_dir() else start.parent
        for _ in range(6):
            # OPT-20260806-057: django 目录退役，锚点切到 conf/base.yaml
            if (here / "conf" / "base.yaml").is_file():
                return here
            here = here.parent
    raise FileNotFoundError("cannot locate monorepo root (expected conf/base.yaml)")


def kebab_to_camel(name: str) -> str:
    parts = name.replace("_", "-").split("-")
    if not parts:
        return name
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def load_yaml(path: Path) -> dict[str, Any]:
    if yaml is None:
        raise RuntimeError("PyYAML required: pip install pyyaml")
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    return data if isinstance(data, dict) else {}


def dump_yaml(path: Path, data: dict[str, Any]) -> None:
    if yaml is None:
        raise RuntimeError("PyYAML required")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        yaml.dump(data, allow_unicode=True, default_flow_style=False, sort_keys=False),
        encoding="utf-8",
    )


def deep_merge(base: dict[str, Any], overlay: dict[str, Any]) -> dict[str, Any]:
    out = dict(base)
    for k, v in overlay.items():
        if k in out and isinstance(out[k], dict) and isinstance(v, dict):
            out[k] = deep_merge(out[k], v)
        elif k in out and isinstance(out[k], list) and isinstance(v, list):
            merged = list(out[k])
            for i, ov in enumerate(v):
                if i < len(merged) and isinstance(merged[i], dict) and isinstance(ov, dict):
                    merged[i] = deep_merge(merged[i], ov)
                elif i < len(merged):
                    merged[i] = ov
                else:
                    merged.append(ov)
            out[k] = merged
        else:
            out[k] = v
    return out


GENERATED_HEADER_RE = re.compile(
    r"^# GENERATED by conf/.+/sync\.sh — DO NOT EDIT\s*$",
    re.MULTILINE,
)

JSON_KEY_TO_APP_DIR = {
    # OPT-20260806-057: django 目录退役，django 键移除，新增语义化目录映射
    "sms": "core/sms",
    "email": "core/email",
    "sso": "core/sso",
    "vue": "frontend/vue",
    "aiProvider": "ai/ai-provider",
    "gitService": "infra/git-service",
    "dockerInfra": "infra/docker-infra",
    "mock_trae_worker": "mock/mock-trae-worker",
        "taskSSE": "gateway/task-sse",
    "taskAgentSupport": "ai/task-agent-support",
    "taskAIEndPoint": "ai/task-ai-endpoint",
    "taskContainerGateway": "gateway/task-container-gateway",
    "taskGateway": "gateway/task-gateway",
    "relayToTrae": "infra/relay-to-trae",
    "taskAuth": "auth/task-auth",
    "taskBill": "billing/task-bill",
    "stripe": "billing/stripe",
    "domainEvents": "events/domain-events",
}


def resolve_conf_app_dir(root: Path, app: str) -> Path:
    """Resolve legacy app key or short name to conf/<functional>/<app>/ directory."""
    key = (app or "").strip().replace("\\", "/").strip("/")
    mapped = JSON_KEY_TO_APP_DIR.get(key, key)
    direct = root / "conf" / mapped
    if (direct / "sync.manifest.yaml").is_file():
        return direct
    tail = key.split("/")[-1]
    conf_root = root / "conf"
    if conf_root.is_dir():
        for func_dir in sorted(conf_root.iterdir()):
            if not func_dir.is_dir() or func_dir.name.startswith("."):
                continue
            candidate = func_dir / tail
            if (candidate / "sync.manifest.yaml").is_file():
                return candidate
    return direct


def generated_header(app_rel_path: str, source: str) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    rel = app_rel_path.strip("/")
    return (
        f"# GENERATED by conf/{rel}/sync.sh — DO NOT EDIT\n"
        f"# source: {source}\n"
        f"# synced_at: {ts}\n"
    )
