-- taskCloudService: Legacy column additions for databases created before dataMigrate
-- Each ALTER TABLE is wrapped in an idempotent check so this file is safe to run
-- on both new databases (where 001_schema.sql already has all columns) and old ones.
-- Applied once via data_migrate_log tracking.

-- Helper: add column if not already present
-- cloud_oauth_tokens legacy columns
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_oauth_tokens' AND COLUMN_NAME = 'company_id') = 0, 'ALTER TABLE cloud_oauth_tokens ADD COLUMN company_id VARCHAR(64) DEFAULT \'\'', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_oauth_tokens' AND COLUMN_NAME = 'platform_type') = 0, 'ALTER TABLE cloud_oauth_tokens ADD COLUMN platform_type VARCHAR(64) DEFAULT \'aliyun\'', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_oauth_tokens' AND COLUMN_NAME = 'authorization_type') = 0, 'ALTER TABLE cloud_oauth_tokens ADD COLUMN authorization_type VARCHAR(64) DEFAULT \'oauth\'', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_oauth_tokens' AND COLUMN_NAME = 'scope') = 0, 'ALTER TABLE cloud_oauth_tokens ADD COLUMN scope TEXT', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;

-- cloud_server_configs legacy columns
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_server_configs' AND COLUMN_NAME = 'container_vscode_url') = 0, 'ALTER TABLE cloud_server_configs ADD COLUMN container_vscode_url VARCHAR(512) DEFAULT \'\'', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_server_configs' AND COLUMN_NAME = 'idle_since') = 0, 'ALTER TABLE cloud_server_configs ADD COLUMN idle_since DATETIME DEFAULT NULL', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_server_configs' AND COLUMN_NAME = 'launch_request_id') = 0, 'ALTER TABLE cloud_server_configs ADD COLUMN launch_request_id VARCHAR(255) DEFAULT \'\'', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_server_configs' AND COLUMN_NAME = 'last_runtime_status') = 0, 'ALTER TABLE cloud_server_configs ADD COLUMN last_runtime_status VARCHAR(64) DEFAULT \'\'', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_server_configs' AND COLUMN_NAME = 'terminal_released') = 0, 'ALTER TABLE cloud_server_configs ADD COLUMN terminal_released TINYINT NOT NULL DEFAULT 0', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_server_configs' AND COLUMN_NAME = 'started_via') = 0, 'ALTER TABLE cloud_server_configs ADD COLUMN started_via VARCHAR(64) DEFAULT \'\'', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_server_configs' AND COLUMN_NAME = 'image_invoker_user_id') = 0, 'ALTER TABLE cloud_server_configs ADD COLUMN image_invoker_user_id VARCHAR(64) DEFAULT \'\'', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_server_configs' AND COLUMN_NAME = 'last_heartbeat_at') = 0, 'ALTER TABLE cloud_server_configs ADD COLUMN last_heartbeat_at DATETIME', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_server_configs' AND COLUMN_NAME = 'verification_secret') = 0, 'ALTER TABLE cloud_server_configs ADD COLUMN verification_secret VARCHAR(255) DEFAULT \'\'', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_server_configs' AND COLUMN_NAME = 'userdata_run_verified') = 0, 'ALTER TABLE cloud_server_configs ADD COLUMN userdata_run_verified DATETIME DEFAULT NULL', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;

-- cloud_server_config_histories legacy columns
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_server_config_histories' AND COLUMN_NAME = 'start_reason') = 0, 'ALTER TABLE cloud_server_config_histories ADD COLUMN start_reason VARCHAR(255) DEFAULT \'\'', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_server_config_histories' AND COLUMN_NAME = 'platform_id') = 0, 'ALTER TABLE cloud_server_config_histories ADD COLUMN platform_id INTEGER DEFAULT 1', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_server_config_histories' AND COLUMN_NAME = 'security_group_id') = 0, 'ALTER TABLE cloud_server_config_histories ADD COLUMN security_group_id VARCHAR(255) DEFAULT \'\'', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_server_config_histories' AND COLUMN_NAME = 'vswitch_id') = 0, 'ALTER TABLE cloud_server_config_histories ADD COLUMN vswitch_id VARCHAR(255) DEFAULT \'\'', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_server_config_histories' AND COLUMN_NAME = 'error_reason') = 0, 'ALTER TABLE cloud_server_config_histories ADD COLUMN error_reason TEXT', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_server_config_histories' AND COLUMN_NAME = 'launch_request_id') = 0, 'ALTER TABLE cloud_server_config_histories ADD COLUMN launch_request_id VARCHAR(255) DEFAULT \'\'', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_server_config_histories' AND COLUMN_NAME = 'cpu_cores') = 0, 'ALTER TABLE cloud_server_config_histories ADD COLUMN cpu_cores INTEGER DEFAULT 1', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_server_config_histories' AND COLUMN_NAME = 'memory_gb') = 0, 'ALTER TABLE cloud_server_config_histories ADD COLUMN memory_gb INTEGER DEFAULT 1', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_server_config_histories' AND COLUMN_NAME = 'storage_gb') = 0, 'ALTER TABLE cloud_server_config_histories ADD COLUMN storage_gb INTEGER DEFAULT 40', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;

-- cloud_tenant_installed_images legacy columns (from old company_id/platform schema)
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_tenant_installed_images' AND COLUMN_NAME = 'tenant_id') = 0, 'ALTER TABLE cloud_tenant_installed_images ADD COLUMN tenant_id VARCHAR(64) DEFAULT \'\'', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_tenant_installed_images' AND COLUMN_NAME = 'external_image_id') = 0, 'ALTER TABLE cloud_tenant_installed_images ADD COLUMN external_image_id VARCHAR(255) DEFAULT \'\'', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_tenant_installed_images' AND COLUMN_NAME = 'description') = 0, 'ALTER TABLE cloud_tenant_installed_images ADD COLUMN description TEXT', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_tenant_installed_images' AND COLUMN_NAME = 'version') = 0, 'ALTER TABLE cloud_tenant_installed_images ADD COLUMN version VARCHAR(64) DEFAULT \'\'', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_tenant_installed_images' AND COLUMN_NAME = 'target_architectures') = 0, 'ALTER TABLE cloud_tenant_installed_images ADD COLUMN target_architectures TEXT', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_tenant_installed_images' AND COLUMN_NAME = 'size') = 0, 'ALTER TABLE cloud_tenant_installed_images ADD COLUMN size INTEGER', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_tenant_installed_images' AND COLUMN_NAME = 'is_dev_mode') = 0, 'ALTER TABLE cloud_tenant_installed_images ADD COLUMN is_dev_mode TINYINT DEFAULT 0', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_tenant_installed_images' AND COLUMN_NAME = 'vendor_id') = 0, 'ALTER TABLE cloud_tenant_installed_images ADD COLUMN vendor_id VARCHAR(64) DEFAULT \'\'', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_tenant_installed_images' AND COLUMN_NAME = 'vendor_name') = 0, 'ALTER TABLE cloud_tenant_installed_images ADD COLUMN vendor_name VARCHAR(255) DEFAULT \'\'', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_tenant_installed_images' AND COLUMN_NAME = 'installed_by_id') = 0, 'ALTER TABLE cloud_tenant_installed_images ADD COLUMN installed_by_id VARCHAR(64) DEFAULT \'\'', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_tenant_installed_images' AND COLUMN_NAME = 'installed_at') = 0, 'ALTER TABLE cloud_tenant_installed_images ADD COLUMN installed_at DATETIME DEFAULT CURRENT_TIMESTAMP', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_tenant_installed_images' AND COLUMN_NAME = 'userdata_template_id') = 0, 'ALTER TABLE cloud_tenant_installed_images ADD COLUMN userdata_template_id VARCHAR(64) DEFAULT \'\'', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_tenant_installed_images' AND COLUMN_NAME = 'auto_run_steps_md') = 0, 'ALTER TABLE cloud_tenant_installed_images ADD COLUMN auto_run_steps_md TEXT', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_tenant_installed_images' AND COLUMN_NAME = 'auto_run_steps_extract_status') = 0, 'ALTER TABLE cloud_tenant_installed_images ADD COLUMN auto_run_steps_extract_status VARCHAR(64) DEFAULT \'\'', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_tenant_installed_images' AND COLUMN_NAME = 'auto_run_steps_digest') = 0, 'ALTER TABLE cloud_tenant_installed_images ADD COLUMN auto_run_steps_digest VARCHAR(255) DEFAULT \'\'', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;

-- cloud_tenant_installed_images data migration: migrate legacy company_id → tenant_id
-- Safe on fresh schemas (skips when company_id column does not exist)
SET @stmt = IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_tenant_installed_images' AND COLUMN_NAME = 'company_id') > 0,
  'UPDATE cloud_tenant_installed_images SET tenant_id = company_id WHERE tenant_id = \'\' AND company_id != \'\'',
  'SELECT 1'
); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;

SET @stmt = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_tenant_installed_images' AND INDEX_NAME = 'idx_tii_tenant') = 0, 'CREATE INDEX idx_tii_tenant ON cloud_tenant_installed_images(tenant_id)', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
