-- Migration 007: Rename tables to conform to service prefix convention.
-- Rule: taskCloudService → cloud_ prefix.
-- Guarded: skips if old table gone or new table already exists (idempotent across restarts).

SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='oauth_tokens') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cloud_oauth_tokens'),'ALTER TABLE `oauth_tokens` RENAME TO `cloud_oauth_tokens`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='tenant_installed_images') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cloud_tenant_installed_images'),'ALTER TABLE `tenant_installed_images` RENAME TO `cloud_tenant_installed_images`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='vendor_cloud_platform_credentials') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cloud_vendor_platform_credentials'),'ALTER TABLE `vendor_cloud_platform_credentials` RENAME TO `cloud_vendor_platform_credentials`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='access_key_iam_associations') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cloud_access_key_iam_associations'),'ALTER TABLE `access_key_iam_associations` RENAME TO `cloud_access_key_iam_associations`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='comment_container_bindings') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cloud_comment_container_bindings'),'ALTER TABLE `comment_container_bindings` RENAME TO `cloud_comment_container_bindings`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='workspace_machine_policies') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cloud_workspace_machine_policies'),'ALTER TABLE `workspace_machine_policies` RENAME TO `cloud_workspace_machine_policies`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='projects_tenant_feature_params') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cloud_tenant_feature_params'),'ALTER TABLE `projects_tenant_feature_params` RENAME TO `cloud_tenant_feature_params`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='projects_workspace_feature_params') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cloud_workspace_feature_params'),'ALTER TABLE `projects_workspace_feature_params` RENAME TO `cloud_workspace_feature_params`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='projects_personal_feature_params_config') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cloud_personal_feature_params_config'),'ALTER TABLE `projects_personal_feature_params_config` RENAME TO `cloud_personal_feature_params_config`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='projects_feature_params_access_audit') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cloud_feature_params_access_audit'),'ALTER TABLE `projects_feature_params_access_audit` RENAME TO `cloud_feature_params_access_audit`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='projects_task_feature_params_snapshot') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cloud_task_feature_params_snapshot'),'ALTER TABLE `projects_task_feature_params_snapshot` RENAME TO `cloud_task_feature_params_snapshot`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='projects_task_api_key_usage') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cloud_task_api_key_usage'),'ALTER TABLE `projects_task_api_key_usage` RENAME TO `cloud_task_api_key_usage`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='projects_workspace_model_budget_default') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cloud_workspace_model_budget_default'),'ALTER TABLE `projects_workspace_model_budget_default` RENAME TO `cloud_workspace_model_budget_default`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='projects_task_model_budget') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cloud_task_model_budget'),'ALTER TABLE `projects_task_model_budget` RENAME TO `cloud_task_model_budget`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='projects_task_model_budget_usage') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cloud_task_model_budget_usage'),'ALTER TABLE `projects_task_model_budget_usage` RENAME TO `cloud_task_model_budget_usage`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='projects_task_model_budget_usage_idempotency') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cloud_task_model_budget_usage_idempotency'),'ALTER TABLE `projects_task_model_budget_usage_idempotency` RENAME TO `cloud_task_model_budget_usage_idempotency`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
SET @stmt = IF(EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='projects_tenant_budget_permission') AND NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='cloud_tenant_budget_permission'),'ALTER TABLE `projects_tenant_budget_permission` RENAME TO `cloud_tenant_budget_permission`','SELECT 1');PREPARE s FROM @stmt;EXECUTE s;DEALLOCATE PREPARE s;
