-- 016: cloud_server_config_defaults 持久化默认硬件筛选字段
-- 背景：前端「设置默认服务器启动配置」已采集 cpu/内存/盘型/实例类型/可用区，
--       但表结构与 API 未落库，导致项目「快速应用默认模版」无法对齐实例筛选区。

SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_server_config_defaults' AND COLUMN_NAME = 'zone_id') = 0, 'ALTER TABLE cloud_server_config_defaults ADD COLUMN zone_id VARCHAR(64) NOT NULL DEFAULT \'\'', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_server_config_defaults' AND COLUMN_NAME = 'cpu_cores') = 0, 'ALTER TABLE cloud_server_config_defaults ADD COLUMN cpu_cores VARCHAR(32) NOT NULL DEFAULT \'\'', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_server_config_defaults' AND COLUMN_NAME = 'memory_gb') = 0, 'ALTER TABLE cloud_server_config_defaults ADD COLUMN memory_gb VARCHAR(32) NOT NULL DEFAULT \'\'', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_server_config_defaults' AND COLUMN_NAME = 'instance_type') = 0, 'ALTER TABLE cloud_server_config_defaults ADD COLUMN instance_type VARCHAR(128) NOT NULL DEFAULT \'\'', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_server_config_defaults' AND COLUMN_NAME = 'system_disk_category') = 0, 'ALTER TABLE cloud_server_config_defaults ADD COLUMN system_disk_category VARCHAR(64) NOT NULL DEFAULT \'cloud_essd\'', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cloud_server_config_defaults' AND COLUMN_NAME = 'data_disk_category') = 0, 'ALTER TABLE cloud_server_config_defaults ADD COLUMN data_disk_category VARCHAR(64) NOT NULL DEFAULT \'cloud_essd\'', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
