/**
 * Extracted from useTaskDetail.js (OPT-20260823-007 line-limit split).
 */
import {
  LAYER_TREE_NODE_PREFIX,
  normalizeLayerGitDirty,
} from '../../utils/layerZtreeNodes.js'
import { layerChangesPayloadImpliesWorktreeDirty } from '../../utils/layerChangesDirty.js'
import {
  CONTAINER_CLONE_PROGRESS_GLOBAL_KEY,
  BOOTSTRAP_CLONE_LOG_INDICATES_DONE_RE,
  createCloneProgressState,
  createCloneProgressComputeds,
  onBootstrapCloneLogUpdate as _onBootstrapCloneLogUpdate,
  rescheduleContainerCloneProgressClearTimer as _rescheduleContainerCloneProgressClearTimer,
  applyBootstrapCloneLogDoneToCloneProgress as _applyBootstrapCloneLogDoneToCloneProgress,
} from './taskDetailCloneProgress.js'
import {
  createTaskDetailZTreeExecLogState,
  installTaskDetailZTreeExecLogWatchers,
  resolveZTreeLogTargets,
  normalizeLayerChangesPayload,
} from './taskDetailZTreeExecLogState.js'

export function buildUseTaskDetailApi(d) {
  const {
    serverStatus, statusMessage, statusCommentId, statusRuntimeStatus, statusTraceId,
    statusProgress, statusLogs, sseLive, isServerRunning, isServerStarting,
    cloudRuntimeStatus, serverUrl, effectiveTenantId, effectiveWorkspaceId,
    effectiveTaskId, workspaceId, backToWorkPanelRoute, detailQuery, forkSourceTaskRoute,
    parentDeliverableRoute, localTask, parentTaskTitle, parentTaskSeq,
    isParentTaskTitleLoading, forkSourceTitle, forkSourceSeq, isForkSourceTitleLoading,
    taskDetailLoading, taskDetailLoadError, taskDetailLoadErrorTraceId, isEditing,
    editingTask, isSaving, editError, layerGraphPushTargetBranch, serverConfigRef,
    collaboratorNameById, collaboratorAvatarById, collaboratorOptions,
    progressStatusOptions, isProgressStatusesLoading, isUpdatingProgressStatus,
    progressStatusError, progressStatusErrorTraceId, taskSubtreeSummary,
    taskSubtreeNodes, isTaskSubtreeLoading, taskSubtreeError, taskSubtreeErrorTraceId,
    deliverableCategoryOptions, isDeliverableCategoriesLoading, deliverableCategoryError,
    isForking, displayComments, activeContainerAgentId, containerForwardCommentId,
    onRepoReclone, commentsHasMore, newComment, commentsFeedsLoadingMore,
    commentComposerChips, removeCommentComposerChip, buildCommentBodyWithChips,
    onCommentTextareaKeydown, submitComment, projectFileTreeRefreshNonce,
    bumpProjectFileTreeRefresh, linkedProjectsPanelRef, workspaceProjects,
    workspaceProjectsLoading, projectServerRunTemplate, repoCloneIdentityByUrl,
    repoCloneIdentitySaveError, repoCloneIdentitySaving, recloneLoadingByUrl,
    recloneStatusByUrl, recloneErrorTraceIdByUrl, repoRecloneGlobalLoading,
    staleRepoSyncLoading, staleRepoSyncError, staleRepoSyncNeedsReclone, repoBranchesCache, repoBranchesLoading,
    repoBranchesErrors, taskProjectsWithDetails, taskRepoRows,
    syncStaleTaskRepoAddresses, syncRepoCloneIdentityMapFromTask, fetchWorkspaceProjects,
    savedRepoCloneIdentityIdForUrl, validateLinkedProjectReposBeforeSendToAi,
    repoCloneIdentityIdForUrl, firstTaskRepoCloneIdentityId, getProjectRepos,
    getRepoBranchValue, setRepoBranch, getRepoBranches, getRepoBranchError,
    isLoadingRepoBranches, fetchRepoBranches, onProjectChange,
    fetchAllLinkedRepoBranches, commonMergeTargetBranchesLoading,
    commonMergeTargetBranchesError, commonMergeTargetBranches, companyUserName,
    isTaskTitleTranslating, taskTitleTranslationError, buildWorkBranchName,
    buildMergeTargetBranchName, fetchCurrentCompanyUserName, applyWorkBranchPreset,
    applyMergeTargetPreset, startEdit, cancelEdit, addProjectAssociation,
    removeProjectAssociation, bindingStatusFor, bindingCscIdFor, bindingContainerNameFor,
    commentHasLiveBinding, commentOwnsSharedContainer, bindingStartTraceIdFor,
    buildPerBindingServerStatusProps, markBindingReconnecting,
    cancelWaitingPreviousBinding, isCancelWaitingBusy, route, router, saveEdit,
    parentDeliverableEditBlockedReason, forkTask, fetchTaskDetail, loadMoreCommentFeeds,
    fetchWorkspaceCollaborators, fetchProgressStatusOptions, fetchTaskSubtree,
    fetchDeliverableCategoryOptions, fetchParentDeliverableTitle, fetchForkSourceTitle,
    layerPanelStore, containerEndpointRegistered, containerPageUrl, containerVscodeUrl,
    displayContainerVscodeUrl, layerGraphSnapshot, cpState, onBootstrapCloneLogUpdate,
    fetchContainerBootstrapCloneLog, hb, selectedLayerGraphNode, layerChangesByLayerId,
    layerGraphCommandText, taskLayerAssociationPanelRef, zlog, containerActionsBlocked,
    layerGraphModelSelectDisabled, onProgressStatusChange, resetLayerGraphFetchBackoff,
    containerBootstrapFailureMessage, containerBootstrapFailureTraceId,
    containerCloneProgressByKey, containerCloneProgressByCommentId,
    containerBootstrapCloneLogFull, containerBootstrapCloneLogSegments,
    containerPageLinkPendingReveal, bootstrapCloneDone,
    cloneProgressBarWidthTransitionClass, cloneProgressRowLogText,
    cloneProgressRowLogDisplayText, cloneProgressRowLogIsPlaceholder,
    containerCloneProgressEntries, cloneProgressEntryByRepoMatchKey,
    containerHttpUnreachable, containerLayerGraphAuthInvalid, containerHeartbeatStatus,
    containerHeartbeatPaused, serverRuntimeNotServing, containerHeartbeatLastSuccess,
    containerHeartbeatAttempts, containerHeartbeatError, containerHeartbeatSeqInfo,
    containerHeartbeatLogLines, appendContainerHeartbeatLogLines,
    markContainerTransportOk, startContainerHeartbeat, stopContainerHeartbeat,
    pauseContainerHeartbeatForRelayStop, resumeContainerHeartbeatForRelayStart,
    isContainerAccessTokenInvalidDetail, formatLayerGraphCommandErrorForUser,
    markContainerTransportUnreachableIfForwardingFailed, probeContainerReachability,
    scheduleContainerUnreachableProbe, clearContainerUnreachableProbeTimer,
    resetServerRuntimeLayerGraphGateCache, layerExecLogLoading, layerExecLogTopError,
    layerCloneLogText, layerCloneLogFetchError, layerCloneLogFetchErrorTraceId,
    layerJobLogFetchError, layerJobLogFetchErrorTraceId, layerJobExecutionPayload,
    layerJobLiveOutputMap, layerChangesRefreshBusy, layerChangesRefreshError,
    layerChangesRefreshErrorTraceId, selectedZTreeLayerChangesPanel,
    selectedLayerGraphFileTreeLayerId, selectedLayerGraphNodeLogKey, zTreeLogTargets,
    layerChangesRefreshEnabled, layerChangesGitStagedActionsBlocked,
    layerChangesGitCommitIdentityBlocked, ingestLayerChangesFromExecutionPayload,
    refreshSelectedLayerChanges, loadMoreSelectedLayerChanges,
    applyLiveLayerChangesToCurrentPayload, layerJobOutputDisplay, layerLiveOutputDisplay,
    layerAgentSteps, layerAgentStepCards, onAgentStepRichInteract, copyAgentStepJson,
    layerJobCommandHead, layerExecLogCopyText, layerExecLogCopyable,
    layerExecLogClearable, layerExecLogCopyFeedback, layerAgentStepCopyFeedbackKey,
    copyLayerExecLog, clearLayerExecLog, prefetchLayerChangeSummariesForDirtyLayers,
    refreshZTreeExecutionLog, activeJobExecLogPoller, layerChangesPrefetchInFlight,
    layerGraphSeenLayerIdSet, layerGraphRefreshing, refreshLayerGraph, layerGraphZNodes,
    layerGraphMetaLine, layerGraphLayerIdsKey, layerGraphCommandKind,
    layerGraphAutoIterationCount, layerGraphModelProvider, layerGraphDefaultModel,
    layerGraphModelOptions, layerGraphSelectedModel, layerGraphModelLoading,
    layerGraphModelLoadError, layerGraphModelLoadErrorTraceId, layerGraphCmdError,
    layerGraphCmdErrorTraceId, layerGraphCmdSending, layerGraphEditRunTargetJobId,
    layerGraphBusyActionKey, layerGraphSelectionDismissedByUser, layerGitIdentityOptions,
    layerGitIdentityLoading, layerGitGithubAppOauthConnected,
    layerRepoGitIdentityLoading, layerRepoGitIdentityFetchError,
    layerRepoGitIdentityRows, perRepoGitIdentitySyncing, perRepoGitIdentitySyncError,
    fetchLayerGraphModelOptions, fetchLayerGitIdentityOptions,
    containerGitIdentityRowForRepoUrl, containerGitIdentityLineForRepoUrl,
    onLayerGraphNodeSelect, callLayerGraphJobAction, callLayerGraphLayerDelete,
    onLayerGraphJobRedo, onLayerGraphJobInterrupt, onLayerGraphJobContinue,
    onLayerGraphJobDelete, onLayerGraphLayerDelete, onLayerGraphJobEditRun,
    pickNewestAddedLayerIdFromSnapshot, normalizeSelectedAgentModels,
    onRepoCloneIdentityChange, submitAIComment, aiStreamBusy, aiStreamBuffer,
    activeAiInstructId, submitLayerGraphCommand, onLayerGraphLayerSubmit,
    onLayerChangesListCommitStaged, onLayerGraphLayerPush, onLayerGraphLayerMerge,
    onLayerGraphLayerSubmitAndPush, onLayerGraphLayerSubmitAndMerge,
    fetchLayerRepoGitIdentities, syncPerRepoGitIdentitiesToContainer,
    rescheduleContainerCloneProgressClearTimer,
    applyBootstrapCloneLogDoneToCloneProgress, fetchContainerTaskUiContext,
    updateServerStatus, handleStartRequestAccepted, onDocumentVisibilityForTaskLayerSync,
    maybeRefreshLayerGraphOnContainerHeartbeatOk, sseConnection, sseReconnectAttempts,
    sseReconnecting, ssePlatformRestartHint, closeSSEConnection,
    handleSSEManualReconnect,
  } = d
  return {
    // Core
    localTask, taskDetailLoading, taskDetailLoadError, taskDetailLoadErrorTraceId, route, router,
    effectiveTenantId, effectiveWorkspaceId, effectiveTaskId, workspaceId,
    backToWorkPanelRoute, detailQuery, forkSourceTaskRoute,
    forkSourceTitle, forkSourceSeq, isForkSourceTitleLoading, fetchForkSourceTitle,
    parentDeliverableRoute, parentTaskTitle, parentTaskSeq, isParentTaskTitleLoading,
    fetchParentDeliverableTitle,
    serverConfigRef, projectFileTreeRefreshNonce, bumpProjectFileTreeRefresh,
    layerGraphPushTargetBranch,
    // SSE & Server
    sseConnection, sseLive, sseReconnecting, sseReconnectAttempts, ssePlatformRestartHint,
    closeSSEConnection, establishSSEConnection: d.establishSSEConnection, handleSSEManualReconnect, handleStartRequestAccepted,
    serverStatus, statusMessage, statusCommentId, statusRuntimeStatus, statusTraceId, statusProgress, statusLogs,
    isServerRunning, isServerStarting, serverUrl, cloudRuntimeStatus,
    serverRuntimeNotServing, containerHeartbeatPaused,
    updateServerStatus,
    // Data
    companyUserName, fetchCurrentCompanyUserName,
    collaboratorNameById, collaboratorAvatarById, collaboratorOptions, fetchWorkspaceCollaborators,
    progressStatusOptions, isProgressStatusesLoading, isUpdatingProgressStatus,
    progressStatusError, progressStatusErrorTraceId, fetchProgressStatusOptions, onProgressStatusChange,
    taskSubtreeSummary, taskSubtreeNodes, isTaskSubtreeLoading,
    taskSubtreeError, taskSubtreeErrorTraceId, fetchTaskSubtree,
    deliverableCategoryOptions, isDeliverableCategoriesLoading, deliverableCategoryError,
    fetchDeliverableCategoryOptions,
    fetchTaskDetail, isForking, forkTask,
    layerGraphModelProvider, layerGraphDefaultModel, layerGraphModelOptions,
    layerGraphSelectedModel, layerGraphModelLoading, layerGraphModelLoadError,
    layerGraphModelLoadErrorTraceId,
    normalizeSelectedAgentModels, fetchLayerGraphModelOptions,
    // Editing
    isEditing, editingTask, isSaving, editError,
    parentDeliverableEditBlockedReason,
    startEdit, cancelEdit, saveEdit,
    isTaskTitleTranslating, taskTitleTranslationError,
    buildWorkBranchName, buildMergeTargetBranchName,
    applyWorkBranchPreset, applyMergeTargetPreset,
    addProjectAssociation, removeProjectAssociation,
    // Projects
    workspaceProjects, workspaceProjectsLoading, fetchWorkspaceProjects,
    projectServerRunTemplate,
    repoCloneIdentityByUrl, repoCloneIdentitySaveError, repoCloneIdentitySaving,
    onRepoCloneIdentityChange,
    recloneLoadingByUrl, recloneStatusByUrl, recloneErrorTraceIdByUrl, repoRecloneGlobalLoading, onRepoReclone,
    taskProjectsWithDetails, taskRepoRows, getProjectRepos,
    staleRepoSyncLoading, staleRepoSyncError, staleRepoSyncNeedsReclone, syncStaleTaskRepoAddresses,
    repoCloneIdentityIdForUrl, firstTaskRepoCloneIdentityId,
    savedRepoCloneIdentityIdForUrl, syncRepoCloneIdentityMapFromTask,
    getRepoBranchValue, setRepoBranch, getRepoBranches, getRepoBranchError,
    isLoadingRepoBranches, fetchRepoBranches, onProjectChange,
    commonMergeTargetBranches, commonMergeTargetBranchesLoading, commonMergeTargetBranchesError,
    fetchAllLinkedRepoBranches,
    validateLinkedProjectReposBeforeSendToAi,
    repoBranchesCache, repoBranchesLoading, repoBranchesErrors,
    // Comments
    newComment, commentComposerChips, displayComments,
    containerForwardCommentId,
    bindingStatusFor, bindingCscIdFor, bindingContainerNameFor,
    commentHasLiveBinding, commentOwnsSharedContainer,
    bindingStartTraceIdFor, buildPerBindingServerStatusProps, markBindingReconnecting,
    cancelWaitingPreviousBinding, isCancelWaitingBusy,
    commentsHasMore, commentsFeedsLoadingMore, loadMoreCommentFeeds,
    removeCommentComposerChip, buildCommentBodyWithChips,
    onCommentTextareaKeydown, submitComment,
    aiStreamBusy, aiStreamBuffer, activeAiInstructId,
    activeContainerAgentId,
    submitAIComment,
    // Container
    containerEndpointRegistered, containerPageUrl, containerVscodeUrl,
    displayContainerVscodeUrl, containerHttpUnreachable, containerLayerGraphAuthInvalid,
    containerHeartbeatStatus, containerHeartbeatLastSuccess,
    containerHeartbeatAttempts, containerHeartbeatError, containerHeartbeatSeqInfo,
    containerHeartbeatLogLines, appendContainerHeartbeatLogLines,
    containerActionsBlocked,
    markContainerTransportOk, markContainerTransportUnreachableIfForwardingFailed,
    formatLayerGraphCommandErrorForUser, isContainerAccessTokenInvalidDetail,
    startContainerHeartbeat, stopContainerHeartbeat,
    pauseContainerHeartbeatForRelayStop, resumeContainerHeartbeatForRelayStart,
    probeContainerReachability, scheduleContainerUnreachableProbe,
    fetchContainerTaskUiContext, onDocumentVisibilityForTaskLayerSync,
    // Clone Progress
    containerCloneProgressByKey, containerCloneProgressByCommentId, containerBootstrapCloneLogFull,
    containerBootstrapCloneLogSegments,
    bootstrapCloneDone,
    containerCloneProgressEntries, cloneProgressEntryByRepoMatchKey,
    cloneProgressBarWidthTransitionClass,
    cloneProgressRowLogText, cloneProgressRowLogDisplayText,
    cloneProgressRowLogIsPlaceholder,
    onBootstrapCloneLogUpdate, applyBootstrapCloneLogDoneToCloneProgress,
    fetchContainerBootstrapCloneLog,
    rescheduleContainerCloneProgressClearTimer,
    containerPageLinkPendingReveal,
    get containerCloneProgressTimer() { return cpState.containerCloneProgressTimer },
    set containerCloneProgressTimer(v) { cpState.containerCloneProgressTimer = v },
    BOOTSTRAP_CLONE_LOG_INDICATES_DONE_RE,
    // Layer Graph
    containerBootstrapFailureMessage, containerBootstrapFailureTraceId,
    layerGraphSnapshot, layerGraphZNodes, layerGraphMetaLine,
    layerPanelStore,
    layerGraphLayerIdsKey, layerGraphSeenLayerIdSet,
    layerGraphRefreshing, refreshLayerGraph,
    selectedLayerGraphNode, selectedLayerGraphFileTreeLayerId,
    layerGraphSelectionDismissedByUser,
    onLayerGraphNodeSelect, pickNewestAddedLayerIdFromSnapshot,
    layerGraphCommandText, layerGraphCommandKind, layerGraphAutoIterationCount,
    layerGraphCmdError, layerGraphCmdErrorTraceId, layerGraphCmdSending,
    layerGraphEditRunTargetJobId, layerGraphBusyActionKey,
    layerGraphModelSelectDisabled, taskLayerAssociationPanelRef,
    applyLayerGraphFromPayload: d.applyLayerGraphFromPayload,
    refreshLayerGraphFromServer: d.refreshLayerGraphFromServer,
    ensureServerRuntimeAllowsContainerLayerGraph: d.ensureServerRuntimeAllowsContainerLayerGraph,
    maybeRefreshLayerGraphOnContainerHeartbeatOk,
    submitLayerGraphCommand,
    onLayerGraphJobRedo, onLayerGraphJobInterrupt,
    onLayerGraphJobContinue, onLayerGraphJobDelete,
    onLayerGraphLayerDelete, onLayerGraphJobEditRun,
    onLayerGraphLayerSubmit, onLayerChangesListCommitStaged,
    onLayerGraphLayerPush,
    onLayerGraphLayerMerge,
    onLayerGraphLayerSubmitAndPush,
    onLayerGraphLayerSubmitAndMerge,
    resetLayerGraphFetchBackoff, resetServerRuntimeLayerGraphGateCache,
    // Execution Log
    layerExecLogLoading, layerExecLogTopError,
    layerCloneLogText, layerCloneLogFetchError, layerCloneLogFetchErrorTraceId,
    layerJobLogFetchError, layerJobLogFetchErrorTraceId, layerJobExecutionPayload, layerJobLiveOutputMap,
    layerChangesByLayerId, layerChangesRefreshBusy, layerChangesRefreshError,
    layerChangesRefreshErrorTraceId,
    layerChangesRefreshEnabled, layerChangesGitStagedActionsBlocked,
    layerChangesGitCommitIdentityBlocked,
    selectedZTreeLayerChangesPanel, selectedLayerGraphNodeLogKey,
    zTreeLogTargets, resolveZTreeLogTargets,
    normalizeLayerChangesPayload, layerChangesPayloadImpliesWorktreeDirty,
    ingestLayerChangesFromExecutionPayload, applyLiveLayerChangesToCurrentPayload,
    refreshSelectedLayerChanges, loadMoreSelectedLayerChanges,
    prefetchLayerChangeSummariesForDirtyLayers,
    layerJobOutputDisplay, layerLiveOutputDisplay,
    layerAgentSteps, layerAgentStepCards, layerJobCommandHead,
    layerExecLogCopyText, layerExecLogCopyable, layerExecLogClearable,
    layerExecLogCopyFeedback, layerAgentStepCopyFeedbackKey,
    copyLayerExecLog, clearLayerExecLog, copyAgentStepJson,
    onAgentStepRichInteract, refreshZTreeExecutionLog,
    callLayerGraphJobAction, callLayerGraphLayerDelete,
    // Git Identity
    layerGitIdentityOptions, layerGitIdentityLoading,
    layerGitGithubAppOauthConnected, fetchLayerGitIdentityOptions,
    layerRepoGitIdentityLoading, layerRepoGitIdentityFetchError,
    layerRepoGitIdentityRows,
    perRepoGitIdentitySyncing, perRepoGitIdentitySyncError,
    fetchLayerRepoGitIdentities, syncPerRepoGitIdentitiesToContainer,
    containerGitIdentityRowForRepoUrl, containerGitIdentityLineForRepoUrl,
    // Template refs
    linkedProjectsPanelRef,
    // Constants / Helpers
    LAYER_TREE_NODE_PREFIX,
    CONTAINER_CLONE_PROGRESS_GLOBAL_KEY,
    // Internal lifecycle state (accessed by TaskDetail.vue lifecycle hooks)
    clearContainerUnreachableProbeTimer: typeof clearContainerUnreachableProbeTimer !== 'undefined' ? clearContainerUnreachableProbeTimer : () => {},
    // Abort helpers
    abortAiInstruct: () => {
      if (typeof d.aiInstructAbortController !== 'undefined' && d.aiInstructAbortController) { d.aiInstructAbortController.abort(); d.aiInstructAbortController = null; }
    },
    abortLayerLog: () => {
      if (zlog.layerLogAbortController) { zlog.layerLogAbortController.abort(); zlog.layerLogAbortController = null; }
    },
    // Cleanup timers
    cleanupExecLogTimers: () => {
      if (zlog.layerExecLogCopyFeedbackTimer) { clearTimeout(zlog.layerExecLogCopyFeedbackTimer); zlog.layerExecLogCopyFeedbackTimer = null; }
      if (zlog.layerAgentStepCopyFeedbackTimer) { clearTimeout(zlog.layerAgentStepCopyFeedbackTimer); zlog.layerAgentStepCopyFeedbackTimer = null; }
      try { activeJobExecLogPoller?.stop?.() } catch { /* ignore */ }
    },
    cleanupContainerTimers: () => {
      if (typeof containerCloneProgressTimer !== 'undefined' && containerCloneProgressTimer !== null) { clearTimeout(cpState.containerCloneProgressTimer); cpState.containerCloneProgressTimer = null; }
    },
    getContainerCloneProgressTimer: () => (cpState && typeof cpState.containerCloneProgressTimer !== 'undefined' ? cpState.containerCloneProgressTimer : null),
    setContainerCloneProgressTimer: (v) => { if (cpState) cpState.containerCloneProgressTimer = v; },
    // Internal state needed by watches
    _internal: {
      get layerGraphHydrateInFlight() { return d.layerGraphHydrateInFlight; },
      set layerGraphHydrateInFlight(v) { d.layerGraphHydrateInFlight = v; },
      get containerUnreachableProbeBackoffMs() { return hb.containerUnreachableProbeBackoffMs; },
      set containerUnreachableProbeBackoffMs(v) { hb.containerUnreachableProbeBackoffMs = v; },
      layerChangesPrefetchInFlight: typeof layerChangesPrefetchInFlight !== 'undefined' ? layerChangesPrefetchInFlight : new Set(),
      CONTAINER_UNREACHABLE_PROBE_BACKOFF_INITIAL_MS: typeof CONTAINER_UNREACHABLE_PROBE_BACKOFF_INITIAL_MS !== 'undefined' ? CONTAINER_UNREACHABLE_PROBE_BACKOFF_INITIAL_MS : 8000,
    },
  }
}
