-- Fix data_migrate_log entries for renumbered migration files.
-- Generated by OPT-20260803-004: resolve dataMigrate numbering conflicts.
-- Run against each affected database.

-- taskAuth
UPDATE data_migrate_log SET step_key = '023_user_archived.sql' WHERE step_key = '003_user_archived.sql';
UPDATE data_migrate_log SET step_key = '024_pkce.sql' WHERE step_key = '004_pkce.sql';
UPDATE data_migrate_log SET step_key = '025_user_profile.sql' WHERE step_key = '013_user_profile.sql';
UPDATE data_migrate_log SET step_key = '026_system_feature_policy.sql' WHERE step_key = '014_system_feature_policy.sql';

-- taskCloudService
UPDATE data_migrate_log SET step_key = '012_cloud_server_events_columns.sql' WHERE step_key = '003_cloud_server_events_columns.sql';

-- taskProjectService
UPDATE data_migrate_log SET step_key = '007_seed_defaults.sql' WHERE step_key = '001_seed_defaults.sql';
UPDATE data_migrate_log SET step_key = '008_rename_tables_prefix.sql' WHERE step_key = '002_rename_tables_prefix.sql';
UPDATE data_migrate_log SET step_key = '009_rename_entity_tables.sql' WHERE step_key = '003_rename_entity_tables.sql';
UPDATE data_migrate_log SET step_key = '010_progress_column_cancelled.sql' WHERE step_key = '005_progress_column_cancelled.sql';

-- taskTaskService
UPDATE data_migrate_log SET step_key = '007_comments_rebuild_drop_user_id.sql' WHERE step_key = '003_comments_rebuild_drop_user_id.sql';
UPDATE data_migrate_log SET step_key = '008_rhythm_windows_rebuild_rhythms.sql' WHERE step_key = '004_rhythm_windows_rebuild_rhythms.sql';
