// @vitest-environment node
/**
 * Onboarding 默认公司名公式 — 与后端 saas.PersonalCompanyName 对齐。
 */
if (!process.env.VITEST) {
  console.log('[skip] onboardingCompanyName.test.js requires vitest runtime')
} else {
const { describe, expect, it } = await import('vitest')
const {
  FALLBACK_PERSONAL_COMPANY_NAME,
  defaultOnboardingCompanyName,
  extractProfileDisplayName,
  isAutoGeneratedCompanyName,
} = await import('./onboardingCompanyName.js')

describe('defaultOnboardingCompanyName', () => {
  it('展示名拼接「的公司」', () => {
    expect(defaultOnboardingCompanyName('张三')).toBe('张三的公司')
    expect(defaultOnboardingCompanyName('  软刀  ')).toBe('软刀的公司')
    expect(defaultOnboardingCompanyName('softknife')).toBe('softknife的公司')
  })

  it('空值或中性占位回退「我的公司」，不重复拼接', () => {
    expect(defaultOnboardingCompanyName('')).toBe(FALLBACK_PERSONAL_COMPANY_NAME)
    expect(defaultOnboardingCompanyName('   ')).toBe(FALLBACK_PERSONAL_COMPANY_NAME)
    expect(defaultOnboardingCompanyName(null)).toBe(FALLBACK_PERSONAL_COMPANY_NAME)
    expect(defaultOnboardingCompanyName(FALLBACK_PERSONAL_COMPANY_NAME)).toBe(
      FALLBACK_PERSONAL_COMPANY_NAME,
    )
  })

  it('已以「的公司」结尾则原样返回', () => {
    expect(defaultOnboardingCompanyName('软刀的公司')).toBe('软刀的公司')
  })
})

describe('extractProfileDisplayName', () => {
  it('优先 personal_nickname', () => {
    expect(extractProfileDisplayName({ personal_nickname: '软刀', username: 'other' })).toBe('软刀')
  })

  it('回退 username / user.username', () => {
    expect(extractProfileDisplayName({ username: 'alice' })).toBe('alice')
    expect(extractProfileDisplayName({ user: { username: 'bob' } })).toBe('bob')
  })
})

describe('isAutoGeneratedCompanyName', () => {
  it('空、我的公司、等于展示名视为自动生成', () => {
    expect(isAutoGeneratedCompanyName('', '软刀')).toBe(true)
    expect(isAutoGeneratedCompanyName('我的公司', '软刀')).toBe(true)
    expect(isAutoGeneratedCompanyName('软刀', '软刀')).toBe(true)
    expect(isAutoGeneratedCompanyName('软刀的公司', '软刀')).toBe(true)
  })

  it('自定义公司名不覆盖', () => {
    expect(isAutoGeneratedCompanyName('Acme', '软刀')).toBe(false)
    expect(isAutoGeneratedCompanyName('现有公司', '软刀')).toBe(false)
  })
})
}
