export const FALLBACK_PERSONAL_COMPANY_NAME = '我的公司'
export const PERSONAL_COMPANY_NAME_SUFFIX = '的公司'

/**
 * 将用户展示名格式化为 onboarding 默认公司名「{user}的公司」。
 * 与后端 saas.PersonalCompanyName 对齐。
 */
export function defaultOnboardingCompanyName(userDisplayName) {
  const name = String(userDisplayName ?? '').trim()
  if (!name || name === FALLBACK_PERSONAL_COMPANY_NAME) {
    return FALLBACK_PERSONAL_COMPANY_NAME
  }
  if (name.endsWith(PERSONAL_COMPANY_NAME_SUFFIX)) {
    return name
  }
  return `${name}${PERSONAL_COMPANY_NAME_SUFFIX}`
}

export function extractProfileDisplayName(profile) {
  return String(
    profile?.personal_nickname ?? profile?.username ?? profile?.user?.username ?? '',
  ).trim()
}

/**
 * 已有公司名是否为自动生成形态（可被「{user}的公司」覆盖）。
 * 自定义名称（如用户已改过）返回 false。
 */
export function isAutoGeneratedCompanyName(existingName, userDisplayName) {
  const existing = String(existingName ?? '').trim()
  if (!existing) return true
  if (existing === FALLBACK_PERSONAL_COMPANY_NAME) return true
  const user = String(userDisplayName ?? '').trim()
  if (!user) return false
  if (existing === user) return true
  if (existing === defaultOnboardingCompanyName(user)) return true
  return false
}
