-- taskTaskService: Legacy column additions for databases created before dataMigrate
-- All columns below are already present in 001_schema.sql; these ALTERs upgrade old DBs.

-- task_tasks legacy columns
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'task_tasks' AND COLUMN_NAME = 'tenant_id') = 0, 'ALTER TABLE task_tasks ADD COLUMN tenant_id VARCHAR(64) DEFAULT ''''', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'task_tasks' AND COLUMN_NAME = 'completed') = 0, 'ALTER TABLE task_tasks ADD COLUMN completed TINYINT DEFAULT 0', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'task_tasks' AND COLUMN_NAME = 'order_num') = 0, 'ALTER TABLE task_tasks ADD COLUMN order_num INTEGER DEFAULT 0', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'task_tasks' AND COLUMN_NAME = 'owner_id') = 0, 'ALTER TABLE task_tasks ADD COLUMN owner_id VARCHAR(64) DEFAULT ''''', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'task_tasks' AND COLUMN_NAME = 'operator_id') = 0, 'ALTER TABLE task_tasks ADD COLUMN operator_id VARCHAR(64) DEFAULT ''''', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'task_tasks' AND COLUMN_NAME = 'deliverable_obj_id') = 0, 'ALTER TABLE task_tasks ADD COLUMN deliverable_obj_id VARCHAR(64) DEFAULT ''''', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'task_tasks' AND COLUMN_NAME = 'progress_column_id') = 0, 'ALTER TABLE task_tasks ADD COLUMN progress_column_id VARCHAR(64) DEFAULT ''''', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'task_tasks' AND COLUMN_NAME = 'parent_task_id') = 0, 'ALTER TABLE task_tasks ADD COLUMN parent_task_id VARCHAR(64) DEFAULT ''''', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'task_tasks' AND COLUMN_NAME = 'fork_from_id') = 0, 'ALTER TABLE task_tasks ADD COLUMN fork_from_id VARCHAR(64) DEFAULT ''''', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'task_tasks' AND COLUMN_NAME = 'installed_image_id') = 0, 'ALTER TABLE task_tasks ADD COLUMN installed_image_id VARCHAR(64) DEFAULT ''''', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'task_tasks' AND COLUMN_NAME = 'auto_run') = 0, 'ALTER TABLE task_tasks ADD COLUMN auto_run TINYINT DEFAULT 0', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'task_tasks' AND COLUMN_NAME = 'auto_commit_after_agent_complete') = 0, 'ALTER TABLE task_tasks ADD COLUMN auto_commit_after_agent_complete TINYINT DEFAULT 0', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'task_tasks' AND COLUMN_NAME = 'feature_params_source') = 0, 'ALTER TABLE task_tasks ADD COLUMN feature_params_source VARCHAR(64) DEFAULT ''company''', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'task_tasks' AND COLUMN_NAME = 'personal_feature_params_config_id') = 0, 'ALTER TABLE task_tasks ADD COLUMN personal_feature_params_config_id VARCHAR(64) DEFAULT ''''', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'task_tasks' AND COLUMN_NAME = 'task_kind') = 0, 'ALTER TABLE task_tasks ADD COLUMN task_kind VARCHAR(64) DEFAULT ''''', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'task_tasks' AND COLUMN_NAME = 'code_lang') = 0, 'ALTER TABLE task_tasks ADD COLUMN code_lang VARCHAR(64) DEFAULT ''''', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;

-- task_comments legacy columns
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'task_comments' AND COLUMN_NAME = 'created_by_id') = 0, 'ALTER TABLE task_comments ADD COLUMN created_by_id VARCHAR(64) DEFAULT ''''', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'task_comments' AND COLUMN_NAME = 'mentions_json') = 0, 'ALTER TABLE task_comments ADD COLUMN mentions_json TEXT', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'task_comments' AND COLUMN_NAME = 'execution_mode') = 0, 'ALTER TABLE task_comments ADD COLUMN execution_mode VARCHAR(64) NOT NULL DEFAULT ''wait_previous''', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'task_comments' AND COLUMN_NAME = 'depends_on_comment_ids') = 0, 'ALTER TABLE task_comments ADD COLUMN depends_on_comment_ids TEXT', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;

-- task_git_identities legacy columns
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'task_git_identities' AND COLUMN_NAME = 'label') = 0, 'ALTER TABLE task_git_identities ADD COLUMN label VARCHAR(255) DEFAULT ''''', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'task_git_identities' AND COLUMN_NAME = 'git_remote_username') = 0, 'ALTER TABLE task_git_identities ADD COLUMN git_remote_username VARCHAR(255) DEFAULT ''''', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
SET @stmt = IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'task_git_identities' AND COLUMN_NAME = 'is_default') = 0, 'ALTER TABLE task_git_identities ADD COLUMN is_default TINYINT DEFAULT 0', 'SELECT 1'); PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
