/**
 * 任务详情「服务器硬件配置」独立组件（云平台、地域、VPC、实例列表与启动等），由 `ServerConfig.logic.vue` 引用。
 */
import { createHardwarePanelCtx } from './createHardwarePanelCtx.js'
import { attachHardwarePanelRunTemplate } from './attachHardwarePanelRunTemplate.js'
import { attachHardwarePanelCloudLoad } from './attachHardwarePanelCloudLoad.js'
import { attachHardwarePanelCloudPlatforms } from './attachHardwarePanelCloudPlatforms.js'
import { attachHardwarePanelStartServer } from './attachHardwarePanelStartServer.js'
import { attachHardwarePanelPricing } from './attachHardwarePanelPricing.js'
import { attachHardwarePanelInstancesFetch } from './attachHardwarePanelInstancesFetch.js'
import { attachHardwarePanelInstancesPage } from './attachHardwarePanelInstancesPage.js'
import { attachHardwarePanelBootstrap } from './attachHardwarePanelBootstrap.js'

/**
 * ServerConfigHardwarePanel 业务状态与副作用。
 * @param {object} props
 * @param {(event: string, ...args: any[]) => void} emit
 * @param {import('vue').Ref<string>} selectedImageId
 */
export function useServerConfigHardwarePanel(props, emit, selectedImageId) {
  const ctx = createHardwarePanelCtx(props, emit, selectedImageId)
  attachHardwarePanelRunTemplate(ctx)
  attachHardwarePanelCloudLoad(ctx)
  attachHardwarePanelCloudPlatforms(ctx)
  attachHardwarePanelStartServer(ctx)
  attachHardwarePanelPricing(ctx)
  attachHardwarePanelInstancesFetch(ctx)
  attachHardwarePanelInstancesPage(ctx)
  attachHardwarePanelBootstrap(ctx)
  return {
    runTemplateMode: ctx.runTemplateMode,
    isServerRunning: ctx.isServerRunning,
    isServerStarting: ctx.isServerStarting,
    serverJumpUrl: ctx.serverJumpUrl,
    serverJumpDefaultPort: ctx.serverJumpDefaultPort,
    panelExpanded: ctx.panelExpanded,
    temporaryConfigExpanded: ctx.temporaryConfigExpanded,
    showProjectTemplateSummaryOnly: ctx.showProjectTemplateSummaryOnly,
    showHardwareConfigForm: ctx.showHardwareConfigForm,
    useProjectTemplateForStart: ctx.useProjectTemplateForStart,
    hardwareConfigSource: ctx.hardwareConfigSource,
    activeHardwareConfigSourceLabel: ctx.activeHardwareConfigSourceLabel,
    resolveTenantId: ctx.resolveTenantId,
    resolveWorkspaceId: ctx.resolveWorkspaceId,
    hasCloudContext: ctx.hasCloudContext,
    getRegionDisplayName: ctx.getRegionDisplayName,
    installedImages: ctx.installedImages,
    cloudPlatforms: ctx.cloudPlatforms,
    regions: ctx.regions,
    zones: ctx.zones,
    vpcs: ctx.vpcs,
    vswitches: ctx.vswitches,
    securityGroups: ctx.securityGroups,
    selectedRegion: ctx.selectedRegion,
    selectedZone: ctx.selectedZone,
    selectedVpc: ctx.selectedVpc,
    selectedSecurityGroup: ctx.selectedSecurityGroup,
    selectedCloudPlatform: ctx.selectedCloudPlatform,
    hardwareBootstrapDone: ctx.hardwareBootstrapDone,
    isLoadingPlatforms: ctx.isLoadingPlatforms,
    isLoadingRegions: ctx.isLoadingRegions,
    isLoadingVpcs: ctx.isLoadingVpcs,
    isLoadingZones: ctx.isLoadingZones,
    previousServerConfig: ctx.previousServerConfig,
    projectRunTemplateApplied: ctx.projectRunTemplateApplied,
    applyServerConfigShape: ctx.applyServerConfigShape,
    resolveShapePlatformId: ctx.resolveShapePlatformId,
    projectTemplateBannerText: ctx.projectTemplateBannerText,
    restoreProjectTemplateDefaults: ctx.restoreProjectTemplateDefaults,
    openTemporaryConfig: ctx.openTemporaryConfig,
    closeTemporaryConfig: ctx.closeTemporaryConfig,
    applyProjectRunTemplateIfNeeded: ctx.applyProjectRunTemplateIfNeeded,
    normalizeDefaultConfigsList: ctx.normalizeDefaultConfigsList,
    resolveInstanceTypeFromServerConfig: ctx.resolveInstanceTypeFromServerConfig,
    findCachedInstanceByType: ctx.findCachedInstanceByType,
    ensureInstanceVisibleOnCurrentPage: ctx.ensureInstanceVisibleOnCurrentPage,
    queueRestoreSelectedInstanceFromTemplate: ctx.queueRestoreSelectedInstanceFromTemplate,
    tryRestorePendingSelectedInstance: ctx.tryRestorePendingSelectedInstance,
    restoreSelectedInstanceFromTemplate: ctx.restoreSelectedInstanceFromTemplate,
    finalizeServerConfigShape: ctx.finalizeServerConfigShape,
    hasConfiguredProjectRunTemplate: ctx.hasConfiguredProjectRunTemplate,
    runTemplateMeta: ctx.runTemplateMeta,
    buildRunTemplatePayload: ctx.buildRunTemplatePayload,
    applyRunTemplate: ctx.applyRunTemplate,
    getLastApplyRunTemplateError: ctx.getLastApplyRunTemplateError,
    hardwareConfig: ctx.hardwareConfig,
    autoReleaseEnabled: ctx.autoReleaseEnabled,
    autoReleaseMinutes: ctx.autoReleaseMinutes,
    DEFAULT_SYSTEM_DISK_CATEGORY: ctx.DEFAULT_SYSTEM_DISK_CATEGORY,
    DEFAULT_STORAGE_TYPES: ctx.DEFAULT_STORAGE_TYPES,
    resolveInstanceStorageTypes: ctx.resolveInstanceStorageTypes,
    resolveInstanceStorageType: ctx.resolveInstanceStorageType,
    filterOptions: ctx.filterOptions,
    cloudPlatformDefaultConfigs: ctx.cloudPlatformDefaultConfigs,
    ensureDefaultConfigForPlatform: ctx.ensureDefaultConfigForPlatform,
    resolveCloudPlatformDefaultConfig: ctx.resolveCloudPlatformDefaultConfig,
    availableInstances: ctx.availableInstances,
    isLoadingInstances: ctx.isLoadingInstances,
    selectedInstance: ctx.selectedInstance,
    pendingRestoreInstanceType: ctx.pendingRestoreInstanceType,
    nextToken: ctx.nextToken,
    isLoadingNextPage: ctx.isLoadingNextPage,
    currentPage: ctx.currentPage,
    pageSize: ctx.pageSize,
    totalPages: ctx.totalPages,
    pageDataCache: ctx.pageDataCache,
    abortPendingAvailableInstancesFetch: ctx.abortPendingAvailableInstancesFetch,
    abortPendingInstanceDetailsFetch: ctx.abortPendingInstanceDetailsFetch,
    releaseAvailableInstancesFetchState: ctx.releaseAvailableInstancesFetchState,
    availableInstancesFetchScheduler: ctx.availableInstancesFetchScheduler,
    scheduleFetchAvailableInstances: ctx.scheduleFetchAvailableInstances,
    instancePrices: ctx.instancePrices,
    priceLoading: ctx.priceLoading,
    bandwidthLimitations: ctx.bandwidthLimitations,
    bandwidthLoading: ctx.bandwidthLoading,
    selectedBandwidth: ctx.selectedBandwidth,
    selectedBandwidthChargingMode: ctx.selectedBandwidthChargingMode,
    DEFAULT_BANDWIDTH: ctx.DEFAULT_BANDWIDTH,
    sdkMethods: ctx.sdkMethods,
    imageArchitectureFromSelection: ctx.imageArchitectureFromSelection,
    imageArchitectureDisplayLabel: ctx.imageArchitectureDisplayLabel,
    imageArchitectureDisplayHint: ctx.imageArchitectureDisplayHint,
    syncImageArchitectureFilterFromSelection: ctx.syncImageArchitectureFilterFromSelection,
    containerImageArchitectureForCloudQuery: ctx.containerImageArchitectureForCloudQuery,
    isServerRuntimeRunning: ctx.isServerRuntimeRunning,
    startServerDisabledReason: ctx.startServerDisabledReason,
    isStartServerDisabled: ctx.isStartServerDisabled,
    startServerButtonLabel: ctx.startServerButtonLabel,
    getStorageMin: ctx.getStorageMin,
    getStorageMax: ctx.getStorageMax,
    fetchImageRegions: ctx.fetchImageRegions,
    loadRegions: ctx.loadRegions,
    loadVpcs: ctx.loadVpcs,
    loadVswitches: ctx.loadVswitches,
    loadZones: ctx.loadZones,
    loadCloudPlatforms: ctx.loadCloudPlatforms,
    fetchPreviousServerConfig: ctx.fetchPreviousServerConfig,
    loadAllCloudPlatformsDefaultConfig: ctx.loadAllCloudPlatformsDefaultConfig,
    handleCloudPlatformChange: ctx.handleCloudPlatformChange,
    applyPreviousConfig: ctx.applyPreviousConfig,
    startServer: ctx.startServer,
    deepEqual: ctx.deepEqual,
    parseBandwidthLimitationResponse: ctx.parseBandwidthLimitationResponse,
    clampBandwidthValue: ctx.clampBandwidthValue,
    onBandwidthInput: ctx.onBandwidthInput,
    onBandwidthBlur: ctx.onBandwidthBlur,
    normalizeInstancePriceRecord: ctx.normalizeInstancePriceRecord,
    getInstancePriceView: ctx.getInstancePriceView,
    selectedInstancePriceView: ctx.selectedInstancePriceView,
    formatPriceAmount: ctx.formatPriceAmount,
    projectTemplateHardwareSummary: ctx.projectTemplateHardwareSummary,
    projectTemplatePriceHint: ctx.projectTemplatePriceHint,
    runTemplateSpecSummary: ctx.runTemplateSpecSummary,
    fetchBandwidthLimitation: ctx.fetchBandwidthLimitation,
    fetchAvailableInstances: ctx.fetchAvailableInstances,
    updateCurrentPageData: ctx.updateCurrentPageData,
    prevPage: ctx.prevPage,
    nextPage: ctx.nextPage,
    handleStorageTypeChange: ctx.handleStorageTypeChange,
    handleStorageSizeChange: ctx.handleStorageSizeChange,
    selectInstance: ctx.selectInstance,
    fetchInstancePrice: ctx.fetchInstancePrice,
    fetchProjectTemplateSummaryPrice: ctx.fetchProjectTemplateSummaryPrice,
    fetchCurrentPageInstancesDetails: ctx.fetchCurrentPageInstancesDetails,
    getResourceName: ctx.getResourceName,
    loadNextPage: ctx.loadNextPage,
    bootstrapCloudPlatformsIfNeeded: ctx.bootstrapCloudPlatformsIfNeeded,
    initHardwareFromParent: ctx.initHardwareFromParent,
    bootstrapManualConfig: ctx.bootstrapManualConfig,
  }
}
