package infrastructure

import (
	"os"
	"path/filepath"
	"testing"

	"gopkg.in/yaml.v3"
)

// OPT-20260810-017：taskAuth 内部密钥（SMS gate 换票 / 厂商申请联系方式门禁）经
// conf/ai/ai-provider/sync.manifest.yaml 从 conf/auth/task-auth/config.yaml 同步到
// 本目录 task-auth.yaml（规则 29：服务仅读本目录配置）。LoadConfig 必须读取该片段，
// 与 taskBill 的 taskAuthInternalSecret 同源。

const aiProviderFragmentPath = "conf/ai/ai-provider/task-auth.yaml"

// writeFragmentWithInternalSecret 临时写入非空 internalSecret 到生成片段，返回恢复函数。
func writeFragmentWithInternalSecret(t *testing.T, root, secret string) {
	t.Helper()
	path := filepath.Join(root, aiProviderFragmentPath)
	orig, origErr := os.ReadFile(path)
	t.Cleanup(func() {
		if origErr != nil {
			_ = os.Remove(path)
			return
		}
		_ = os.WriteFile(path, orig, 0o644)
	})
	body := "# GENERATED by conf/ai/ai-provider/sync.sh — DO NOT EDIT\n" +
		"# source: conf/auth/task-auth/config.yaml\n" +
		"internalSecret: " + secret + "\n"
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func TestLoadConfigReadsSyncedTaskAuthFragment(t *testing.T) {
	root, err := FindMonorepoRoot()
	if err != nil {
		t.Fatalf("FindMonorepoRoot: %v", err)
	}
	// 清除 env 覆盖，让 LoadConfig 回退到本目录 sync 片段（置空等价未设置）。
	t.Setenv("TASKAUTH_INTERNAL_SECRET", "")
	t.Setenv("X_INTERNAL_SECRET", "")
	writeFragmentWithInternalSecret(t, root, "synced-fragment-secret")

	cfg, err := LoadConfig(root)
	if err != nil {
		t.Fatalf("LoadConfig: %v", err)
	}
	if cfg.TaskAuthInternalSecret != "synced-fragment-secret" {
		t.Fatalf("TaskAuthInternalSecret = %q, want %q — LoadConfig 未读 sync 片段 task-auth.yaml",
			cfg.TaskAuthInternalSecret, "synced-fragment-secret")
	}
}

func TestTaskAuthInternalSecretEnvWinsOverFragment(t *testing.T) {
	root, err := FindMonorepoRoot()
	if err != nil {
		t.Fatalf("FindMonorepoRoot: %v", err)
	}
	t.Setenv("TASKAUTH_INTERNAL_SECRET", "env-secret")
	t.Setenv("X_INTERNAL_SECRET", "")
	writeFragmentWithInternalSecret(t, root, "fragment-secret")

	cfg, err := LoadConfig(root)
	if err != nil {
		t.Fatalf("LoadConfig: %v", err)
	}
	if cfg.TaskAuthInternalSecret != "env-secret" {
		t.Fatalf("TaskAuthInternalSecret = %q, want %q — env 覆盖应优先于 sync 片段",
			cfg.TaskAuthInternalSecret, "env-secret")
	}
}

// TestSyncManifestDeclaresTaskAuthFragment 守护 sync.manifest 声明：若片段被误删，
// 服务将失去与 taskBill 同源的 taskAuth 内部密钥（规则 29 合规路径）。
func TestSyncManifestDeclaresTaskAuthFragment(t *testing.T) {
	root, err := FindMonorepoRoot()
	if err != nil {
		t.Fatalf("FindMonorepoRoot: %v", err)
	}
	data, err := os.ReadFile(filepath.Join(root, "conf", "ai", "ai-provider", "sync.manifest.yaml"))
	if err != nil {
		t.Fatalf("read sync.manifest.yaml: %v", err)
	}
	var manifest struct {
		Fragments []struct {
			From string   `yaml:"from"`
			To   string   `yaml:"to"`
			Pick []string `yaml:"pick"`
		} `yaml:"fragments"`
	}
	if err := yaml.Unmarshal(data, &manifest); err != nil {
		t.Fatalf("parse sync.manifest.yaml: %v", err)
	}
	for _, f := range manifest.Fragments {
		if f.From == "../../auth/task-auth/config.yaml" && f.To == "task-auth.yaml" {
			for _, k := range f.Pick {
				if k == "internalSecret" {
					return
				}
			}
		}
	}
	t.Fatal("sync.manifest.yaml 缺少 from ../../auth/task-auth/config.yaml 且 pick internalSecret 的片段（OPT-20260810-017）")
}
