import {
  userdataVarsExcludingReservedEnv,
  linuxBusinessApiSetupSnippet,
  linuxDockerEnvBusinessApiAppend,
  linuxBootProgressReportSnippet,
} from './userDataTemplate.js'

/**
 * Generate Linux bash container initialization script.
 * Pure function — returns script string, no side effects.
 *
 * 运行时身份（token / 云前缀 / 容器名 / comment / trace / 镜像）一律写 __TASK2APP_* 占位符，
 * 由 start-vm → RunInstances 前 replaceUserdataRuntimePlaceholders 注入真实值。
 */
export function generateLinuxScript(params) {
  const {
    osLabel, linuxFamily, containerName, containerPort, hostPort, volumes,
    containerUser, containerWorkdir, containerCommand, containerEntryPoint,
    runtime, privileged, restartPolicy, businessHostPort, businessContainerPort,
    businessApiEndpointExplicit, taskApiEndpoint, accessToken, containerImage,
    commentId, traceId, userdataVars, form,
  } = params

  const shCommand = (cmd) => `echo "${cmd}"`
  const userEnvVarsExport = userdataVarsExcludingReservedEnv(userdataVars)
    .map(v => `export ${v.name}='${v.value || ''}'`).join('\n')
  const userEnvVarsDocker = userdataVarsExcludingReservedEnv(userdataVars)
    .map(v => `RUN_CMD="$RUN_CMD -e ${v.name}='${v.value || ''}'"`).join('\n')

  const phAccess = accessToken || '__TASK2APP_ACCESS_TOKEN__'
  const phEndpoint = taskApiEndpoint || '__TASK2APP_TASK_CLOUD_PREFIX__'
  const phName = containerName || '__TASK2APP_CONTAINER_NAME__'
  const phComment = commentId || '__TASK2APP_COMMENT_ID__'
  const phTrace = traceId || '__TASK2APP_TRACE_ID__'
  const phImage = containerImage || '__TASK2APP_CONTAINER_IMAGE__'

  return `#!/bin/bash
# ========================
# Container Initialization Script for ${osLabel}
# Generated by Task2App Platform
# ========================

${shCommand('开始容器初始化...')}
${shCommand('操作系统: ' + osLabel)}

# 错误处理
set -e

# 日志函数
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

# 检查 root 权限
if [ "$EUID" -ne 0 ]; then
    log "错误: 请使用 root 权限运行此脚本"
    exit 1
fi

# 尽早注入任务云前缀与预埋 Access（均为 __TASK2APP_* 占位符，RunInstances 前替换）
# COMMENT_ID / TRACE_ID / CONTAINER_NAME / ACCESS_TOKEN / TASK_API_ENDPOINT 禁止在模板写真实值
export ACCESS_TOKEN='${phAccess}'
export TASK_API_ENDPOINT='${phEndpoint}'
export CONTAINER_NAME='${phName}'
export COMMENT_ID='${phComment}'
export TRACE_ID='${phTrace}'

${linuxBootProgressReportSnippet()}

report_progress 5 "开始容器初始化"

# 检测操作系统类型
OS_FAMILY="${linuxFamily}"
RUNTIME="${runtime}"

# 安装基础依赖
report_progress 10 "安装基础依赖..."
if [ "$OS_FAMILY" = "centos" ]; then
    yum install -y yum-utils device-mapper-persistent-data lvm2 ca-certificates curl
elif [ "$OS_FAMILY" = "ubuntu" ]; then
    apt-get update
    apt-get install -y ca-certificates curl gnupg lsb-release
elif [ "$OS_FAMILY" = "debian" ]; then
    apt-get update
    apt-get install -y ca-certificates curl gnupg lsb-release
fi
report_progress 15 "基础依赖安装完成"

# 安装 Docker Engine
report_progress 20 "安装容器运行时..."

if [ "$RUNTIME" = "podman" ]; then
    log "使用 Podman 容器运行时..."

    if [ "$OS_FAMILY" = "centos" ]; then
        yum install -y podman
    elif [ "$OS_FAMILY" = "ubuntu" ]; then
        apt-get install -y podman
    elif [ "$OS_FAMILY" = "debian" ]; then
        apt-get install -y podman
    fi

    CONTAINER_CMD="podman"
else
    log "使用 Docker 容器运行时..."

    # 国内云主机常无法直连 download.docker.com（TLS reset）；优先阿里云/清华镜像，官方兜底
    # 已安装则跳过，避免重复装包失败打断 UserData
    if command -v docker >/dev/null 2>&1; then
        log "检测到已安装 docker，跳过 Docker Engine 安装"
    elif [ "$OS_FAMILY" = "centos" ]; then
        DOCKER_CE_OK=0
        for _repo in \\
          "https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo" \\
          "https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/centos/docker-ce.repo" \\
          "https://download.docker.com/linux/centos/docker-ce.repo"; do
            if yum-config-manager --add-repo "\$_repo" 2>/dev/null; then
                if yum install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin; then
                    DOCKER_CE_OK=1
                    log "Docker CE 已从仓库安装: \$_repo"
                    break
                fi
            fi
        done
        if [ "\$DOCKER_CE_OK" -ne 1 ]; then
            log "错误: Docker CE 安装失败（centos 镜像源均不可用）"
            exit 1
        fi
    elif [ "$OS_FAMILY" = "ubuntu" ] || [ "$OS_FAMILY" = "debian" ]; then
        mkdir -p /etc/apt/keyrings
        DOCKER_CE_OK=0
        DOCKER_CE_MIRROR=""
        for DOCKER_CE_MIRROR in \\
          "https://mirrors.aliyun.com/docker-ce/linux/\${OS_FAMILY}" \\
          "https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/\${OS_FAMILY}" \\
          "https://download.docker.com/linux/\${OS_FAMILY}"; do
            rm -f /etc/apt/keyrings/docker.gpg
            if curl -fsSL "\${DOCKER_CE_MIRROR}/gpg" 2>/dev/null | gpg --dearmor -o /etc/apt/keyrings/docker.gpg \\
              && [ -s /etc/apt/keyrings/docker.gpg ]; then
                echo "deb [arch=\$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \${DOCKER_CE_MIRROR} \$(lsb_release -cs) stable" \\
                  | tee /etc/apt/sources.list.d/docker.list > /dev/null
                if apt-get update \\
                  && apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin; then
                    DOCKER_CE_OK=1
                    log "Docker CE 已从镜像安装: \${DOCKER_CE_MIRROR}"
                    break
                fi
            fi
            log "警告: Docker CE 镜像不可用，尝试下一个: \${DOCKER_CE_MIRROR}"
        done
        if [ "\$DOCKER_CE_OK" -ne 1 ]; then
            log "错误: Docker CE 安装失败（GPG/仓库均不可达，含 download.docker.com）"
            exit 1
        fi
    fi

    CONTAINER_CMD="docker"
fi
report_progress 35 "容器运行时安装完成"

# 启动容器运行时
report_progress 40 "启动 ${runtime} 服务..."

if [ "$RUNTIME" = "podman" ]; then
    systemctl enable --now podman 2>/dev/null || podman system service -t 0 &
else
    systemctl enable docker
    systemctl start docker
fi

# 等待服务就绪
report_progress 45 "等待容器运行时服务就绪..."
max_wait=60
waited=0
while ! \${CONTAINER_CMD} info &>/dev/null && [ $waited -lt $max_wait ]; do
    sleep 2
    waited=$((waited + 2))
done

if ! \${CONTAINER_CMD} info &>/dev/null; then
    log "错误: 容器运行时服务未能启动"
    exit 1
fi

report_progress 55 "容器运行时服务已就绪"

# 拉取容器镜像（占位符，RunInstances 前替换）
CONTAINER_IMAGE='${phImage}'
report_progress 60 "拉取容器镜像: $CONTAINER_IMAGE"

\${CONTAINER_CMD} pull "$CONTAINER_IMAGE"
if [ $? -ne 0 ]; then
    log "错误: 镜像拉取失败"
    exit 1
fi

report_progress 70 "镜像拉取成功"

# 使用宿主机网络（无 -p 端口映射）
log "容器网络: host"

# 用户自定义环境变量
${userEnvVarsExport}

# 构建容器运行命令（容器名用已 export 的 CONTAINER_NAME，禁止再写死字面量）
HOST_PORT='${hostPort}'
CONTAINER_PORT='${containerPort}'
BUSINESS_HOST_PORT='${businessHostPort}'
BUSINESS_CONTAINER_PORT='${businessContainerPort}'
VOLUMES='${volumes}'
CONTAINER_USER='${containerUser}'
CONTAINER_WORKDIR='${containerWorkdir}'
CONTAINER_COMMAND='${containerCommand}'
CONTAINER_ENTRYPOINT='${containerEntryPoint}'
RESTART_POLICY='${restartPolicy}'
PRIVILEGED='${privileged}'

${linuxBusinessApiSetupSnippet(businessApiEndpointExplicit, true)}

# 停止并移除已存在的同名容器
if \${CONTAINER_CMD} ps -a --format "{{.Names}}" | grep -q "^\${CONTAINER_NAME}$"; then
    log "停止并移除已存在的容器: \${CONTAINER_NAME}"
    \${CONTAINER_CMD} stop "\${CONTAINER_NAME}" 2>/dev/null || true
    \${CONTAINER_CMD} rm "\${CONTAINER_NAME}" 2>/dev/null || true
fi

# 构建运行命令（--network host，无端口映射）
RUN_CMD="\${CONTAINER_CMD} run -d --network host --name \${CONTAINER_NAME}"

# 添加环境变量
RUN_CMD="$RUN_CMD -e ACCESS_TOKEN='$ACCESS_TOKEN'"
RUN_CMD="$RUN_CMD -e TASK_API_ENDPOINT='$TASK_API_ENDPOINT'"
RUN_CMD="$RUN_CMD -e CONTAINER_NAME='$CONTAINER_NAME'"
RUN_CMD="$RUN_CMD -e COMMENT_ID='$COMMENT_ID'"
RUN_CMD="$RUN_CMD -e TRACE_ID='$TRACE_ID'"

${userEnvVarsDocker}

${linuxDockerEnvBusinessApiAppend()}

# 添加卷挂载
if [ -n "$VOLUMES" ]; then
    OLD_IFS="$IFS"
    IFS=';'
    for vol in $VOLUMES; do
        if [ -n "$vol" ]; then
            RUN_CMD="$RUN_CMD -v $vol"
        fi
    done
    IFS="$OLD_IFS"
fi

# 添加特权模式
if [ "$PRIVILEGED" = "true" ]; then
    RUN_CMD="$RUN_CMD --privileged"
fi

# 添加重启策略
RUN_CMD="$RUN_CMD --restart $RESTART_POLICY"

# 添加工作目录
if [ -n "$CONTAINER_WORKDIR" ]; then
    RUN_CMD="$RUN_CMD -w $CONTAINER_WORKDIR"
fi

# 添加用户
if [ -n "$CONTAINER_USER" ]; then
    RUN_CMD="$RUN_CMD -u $CONTAINER_USER"
fi

# 添加入口点
if [ -n "$CONTAINER_ENTRYPOINT" ]; then
    RUN_CMD="$RUN_CMD --entrypoint $CONTAINER_ENTRYPOINT"
fi

# 添加命令
if [ -n "$CONTAINER_COMMAND" ]; then
    RUN_CMD="$RUN_CMD $CONTAINER_COMMAND"
fi

# 添加镜像
RUN_CMD="$RUN_CMD $CONTAINER_IMAGE"

# 启动容器
report_progress 75 "启动容器..."
log "执行命令: $RUN_CMD"

bash -c "$RUN_CMD"

if [ $? -eq 0 ]; then
    report_progress 85 "容器启动成功"
    \${CONTAINER_CMD} ps --filter "name=\${CONTAINER_NAME}"
else
    log "错误: 容器启动失败"
    exit 1
fi

# 等待容器完全启动
report_progress 88 "等待容器完全启动..."
sleep 10

# 自动验证脚本
report_progress 90 "开始自动验证..."

# 检查容器状态（须用已 export 的 CONTAINER_NAME；禁止未定义的 camelCase 变量——
# RunInstances 曾误把 shell 容器名引用值注入为平台路由名或 "-"，
# 导致 docker inspect 失败、脚本 exit 1、服务器状态卡在「启动中」、verify 回调不触发）
containerStatus=$(\${CONTAINER_CMD} inspect -f '{{.State.Status}}' "\${CONTAINER_NAME}" 2>/dev/null)
if [ "$containerStatus" = "running" ]; then
    log "容器状态检查通过: 运行中"
else
    log "错误: 容器状态异常 - $containerStatus"
    exit 1
fi

# 检查端口是否在监听
portToCheck=\${HOST_PORT}
maxWait=30
waited=0
portListening=false

while [ "$portListening" = "false" ] && [ \$waited -lt \$maxWait ]; do
    if netstat -tuln 2>/dev/null | grep -q ":\${portToCheck} " || ss -tuln 2>/dev/null | grep -q ":\${portToCheck} "; then
        portListening=true
        break
    fi
    sleep 2
    waited=$((waited + 2))
done

if [ "$portListening" = "true" ]; then
    log "端口 $portToCheck 检查通过: 正在监听"
else
    log "警告: 端口 $portToCheck 未开始监听"
fi

# 如果配置了自动验证脚本，执行自定义验证
autoVerifyScript='${form.auto_verify_script || ''}'
if [ -n "$autoVerifyScript" ]; then
    log "执行自定义自动验证脚本..."
    eval "$autoVerifyScript"
    log "自定义验证脚本执行完成"
else
    # 默认验证：检查容器进程是否存在（同 inspect：用已 export 的容器名）
    containerProcess=$(\${CONTAINER_CMD} top "\${CONTAINER_NAME}" 2>/dev/null)
    if [ -n "$containerProcess" ]; then
        log "容器进程检查通过"
    else
        log "警告: 无法获取容器进程信息"
    fi
fi

report_progress 95 "容器初始化完成"
log "==============================="
`
}
