import {
  userdataVarsExcludingReservedEnv,
  powershellBusinessApiEnvBlock,
  powershellBootProgressReportSnippet,
} from './userDataTemplate.js'

/**
 * Generate Windows PowerShell container initialization script.
 * Pure function — returns script string, no side effects.
 */
export function generateWindowsScript(params) {
  const {
    osLabel, containerName, volumes, containerUser, containerWorkdir,
    containerCommand, containerEntryPoint, privileged, restartPolicy,
    businessHostPort, businessApiEndpointExplicit, hostPort,
    taskApiEndpoint, accessToken, containerImage, commentId, traceId,
    userdataVars, form,
  } = params

  const psCommand = (cmd) => `Write-Output "${cmd}"`
  const userEnvVars = userdataVarsExcludingReservedEnv(userdataVars)
    .map(v => `$envVars['${v.name}'] = '${v.value || ''}'`).join('\n')

  const phAccess = accessToken || '__TASK2APP_ACCESS_TOKEN__'
  const phEndpoint = taskApiEndpoint || '__TASK2APP_TASK_CLOUD_PREFIX__'
  const phName = containerName || '__TASK2APP_CONTAINER_NAME__'
  const phComment = commentId || '__TASK2APP_COMMENT_ID__'
  const phTrace = traceId || '__TASK2APP_TRACE_ID__'
  const phImage = containerImage || '__TASK2APP_CONTAINER_IMAGE__'

  return `#ps1
# ========================
# Container Initialization Script for ${osLabel}
# Generated by Task2App Platform
# ========================

${psCommand('开始容器初始化...')}
${psCommand('操作系统: ' + osLabel)}

# 检查管理员权限
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Write-Output "错误: 请以管理员身份运行此脚本"
    exit 1
}

# 尽早注入任务云前缀与预埋 Access（均为 __TASK2APP_* 占位符，RunInstances 前替换）
$env:ACCESS_TOKEN = '${phAccess}'
$env:TASK_API_ENDPOINT = '${phEndpoint}'
$env:CONTAINER_NAME = '${phName}'
$env:COMMENT_ID = '${phComment}'
$env:TRACE_ID = '${phTrace}'

${powershellBootProgressReportSnippet()}

Report-Progress -Progress 5 -Message "开始容器初始化"

# 安装 Chocolatey (如果未安装)
if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
    Report-Progress -Progress 10 -Message "安装 Chocolatey 包管理器..."
    Set-ExecutionPolicy Bypass -Scope Process -Force
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
    Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
}

# 安装 Docker Desktop 或 Docker Engine
Report-Progress -Progress 20 -Message "安装 Docker..."
if (Get-Command docker -ErrorAction SilentlyContinue) {
    ${psCommand('Docker 已安装')}
} else {
    ${psCommand('通过 Chocolatey 安装 Docker...')}
    choco install docker-desktop -y --force
}
Report-Progress -Progress 35 -Message "Docker 安装完成"

# 等待 Docker 服务启动
Report-Progress -Progress 40 -Message "等待 Docker 服务启动..."
$maxWait = 60
$waited = 0
while (-not (docker info 2>$null) -and $waited -lt $maxWait) {
    Start-Sleep -Seconds 2
    $waited += 2
}

if (-not (docker info 2>$null)) {
    Write-Output "错误: Docker 服务未能启动"
    exit 1
}
Report-Progress -Progress 55 -Message "Docker 服务已就绪"

# 拉取容器镜像（占位符，RunInstances 前替换）
Report-Progress -Progress 60 -Message "拉取容器镜像..."
$image = '${phImage}'
docker pull $image
Report-Progress -Progress 70 -Message "镜像拉取成功"

# 使用宿主机网络（无 -p 端口映射）
${psCommand('容器网络: host')}

# 构建容器运行命令（用已注入的 CONTAINER_NAME）
$containerName = $env:CONTAINER_NAME

# 停止并移除已存在的同名容器
if (docker ps -a --format '{{.Names}}' | Select-String -Quiet "^$containerName$") {
    Write-Output "移除已存在的容器: $containerName"
    docker stop $containerName 2>$null
    docker rm $containerName 2>$null
}

# 构建环境变量
$envVars = @{}
$envVars['ACCESS_TOKEN'] = $env:ACCESS_TOKEN
$envVars['TASK_API_ENDPOINT'] = $env:TASK_API_ENDPOINT
$envVars['CONTAINER_NAME'] = $containerName
$envVars['COMMENT_ID'] = $env:COMMENT_ID
$envVars['TRACE_ID'] = $env:TRACE_ID

# 用户自定义环境变量
${userEnvVars}

${powershellBusinessApiEnvBlock(businessHostPort, businessApiEndpointExplicit)}

# 构建 Docker 运行命令（--network host，无端口映射）
$runCmd = "docker run -d --network host --name " + $containerName

# 添加环境变量
foreach ($key in $envVars.Keys) {
    $runCmd += " -e " + $key + "=" + $envVars[$key]
}

# 添加卷挂载
$volumes = '${volumes}'
if ($volumes) {
    $volumeList = $volumes -split ';'
    foreach ($vol in $volumeList) {
        if ($vol) {
            $runCmd += " -v " + $vol
        }
    }
}

# 添加特权模式
if ('${privileged}' -eq 'true') {
    $runCmd += " --privileged"
}

# 添加重启策略
$runCmd += " --restart ${restartPolicy}"

# 添加工作目录
$workdir = '${containerWorkdir}'
if ($workdir) {
    $runCmd += " -w " + $workdir
}

# 添加用户
$runAsUser = '${containerUser}'
if ($runAsUser) {
    $runCmd += " -u " + $runAsUser
}

# 添加入口点
$entryPoint = '${containerEntryPoint}'
if ($entryPoint) {
    $runCmd += " --entrypoint " + $entryPoint
}

# 添加命令
$cmd = '${containerCommand}'
if ($cmd) {
    $runCmd += " " + $cmd
}

# 添加镜像
$runCmd += " " + $image

Report-Progress -Progress 75 -Message "启动容器..."
Write-Output "执行命令: $runCmd"

# 执行命令
Invoke-Expression $runCmd

if ($LASTEXITCODE -eq 0) {
    Report-Progress -Progress 85 -Message "容器启动成功"
    docker ps --filter "name=$containerName"
} else {
    Write-Output "错误: 容器启动失败"
    exit 1
}

# 等待容器完全启动
Report-Progress -Progress 88 -Message "等待容器完全启动..."
Start-Sleep -Seconds 10

# 自动验证脚本
Report-Progress -Progress 90 -Message "开始自动验证..."

# 检查容器状态
$containerStatus = docker inspect -f '{{.State.Status}}' $containerName 2>$null
if ($containerStatus -eq 'running') {
    ${psCommand('容器状态检查通过: 运行中')}
} else {
    Write-Output "错误: 容器状态异常 - $containerStatus"
    exit 1
}

# 检查端口是否在监听
$portToCheck = '${hostPort || '8080'}'
$maxWait = 30
$waited = 0
$portListening = $false

while (-not $portListening -and $waited -lt $maxWait) {
    $connections = netstat -an | Select-String "LISTENING" | Select-String ":$portToCheck"
    if ($connections) {
        $portListening = $true
        break
    }
    Start-Sleep -Seconds 2
    $waited += 2
}

if ($portListening) {
    ${psCommand("端口 $portToCheck 检查通过: 正在监听")}
} else {
    Write-Output "警告: 端口 $portToCheck 未开始监听"
}

# 如果配置了自动验证脚本，执行自定义验证
$autoVerifyScript = @'
${form.auto_verify_script || ''}
'@
if ($autoVerifyScript -and $autoVerifyScript.Trim()) {
    ${psCommand('执行自定义自动验证脚本...')}
    try {
        Invoke-Expression $autoVerifyScript
        ${psCommand('自定义验证脚本执行完成')}
    } catch {
        Write-Output "警告: 自定义验证脚本执行失败 - $_"
    }
} else {
    # 默认验证：检查容器进程是否存在
    $containerProcess = docker top $containerName 2>$null
    if ($containerProcess) {
        ${psCommand('容器进程检查通过')}
    } else {
        Write-Output "警告: 无法获取容器进程信息"
    }
}

Report-Progress -Progress 95 -Message "容器初始化完成"
${psCommand('=' * 50)}
`
}
